import { redirect,notFound } from 'next/navigation';
import { platformContext,PlatformAccessError } from '@/lib/platform';
import { z } from 'zod';
import { formatMoney } from '@/lib/money';
import { PrintButton } from '@/components/print-button';
export const dynamic='force-dynamic';
export default async function Receipt({params}:{params:Promise<{id:string}>}){
 let context;try{context=await platformContext();}catch(e){if(e instanceof PlatformAccessError&&e.status===401)redirect('/login');if(e instanceof PlatformAccessError)redirect('/superadmin/mfa');throw e;}
 const {client}=context;const id=z.uuid().parse((await params).id);const payment=await client.from('platform_payments').select('*').eq('id',id).single();if(payment.error||!payment.data)notFound();const p=payment.data;
 const [business,method,applications,settings]=await Promise.all([client.from('platform_businesses').select('commercial_name,owner_name,owner_email').eq('academy_id',p.academy_id).single(),client.from('platform_payment_methods').select('name').eq('id',p.method_id).single(),client.from('platform_applications').select('charge_id,amount').eq('payment_id',id),client.from('platform_settings').select('contact,timezone').single()]);if(business.error||method.error||applications.error||settings.error)throw Error('No se pudo emitir el comprobante.');
 const chargeIds=applications.data.map(a=>a.charge_id);const charges=await client.from('platform_charges').select('id,description,period_on').in('id',chargeIds);if(charges.error)throw Error('No se pudieron consultar los cargos.');
 return <main className="receipt-page"><header className="receipt-header"><div><span className="eyebrow">COMPROBANTE ADMINISTRATIVO · PLATAFORMA</span><h1>Suscripción de servicio</h1><p>{settings.data.contact}</p></div><div><strong>Comprobante #{p.receipt_number}</strong><p>{new Date(p.created_at).toLocaleString('es-NI',{timeZone:settings.data.timezone})}</p></div></header><div className="receipt-meta"><p>Negocio: <strong>{business.data.commercial_name}</strong></p><p>Propietario: {business.data.owner_name} · {business.data.owner_email}</p><p>Medio: {method.data.name} · Estado: <strong>{p.status}</strong></p>{p.reference&&<p>Referencia: {p.reference}</p>}{p.status!=='confirmado'&&<div className="notice">Este registro no acredita un pago confirmado ni salda la deuda.</div>}</div><table><thead><tr><th>Concepto</th><th>Período</th><th>Aplicación</th></tr></thead><tbody>{applications.data.map(line=>{const charge=charges.data.find(c=>c.id===line.charge_id);return <tr key={line.charge_id}><td>{charge?.description}</td><td>{charge?.period_on}</td><td>{formatMoney(line.amount,p.currency)}</td></tr>;})}</tbody></table><div className="receipt-total">Total: {formatMoney(p.amount,p.currency)}</div><footer className="receipt-footer"><p>Comprobante administrativo del servicio de plataforma. Conserva este documento para tu control.</p><PrintButton/></footer></main>;
}
