import { test,expect } from '@playwright/test';
import { Temporal } from '@js-temporal/polyfill';
test('venta, gasto, cierre, clase y asistencia desde los formularios',async({page},testInfo)=>{
 test.setTimeout(90000);
 await page.goto('/login');await page.getByLabel('Correo electrónico').fill('owner@test.invalid');await page.getByLabel('Contraseña',{exact:true}).fill('test-only-password-123');await page.getByRole('button',{name:'Entrar a la academia'}).click();await expect(page.getByRole('heading',{name:'Hola, Propietario'})).toBeVisible();
 const scope=await (await page.request.get('http://127.0.0.1:54321/test/context')).json();const suffix=testInfo.project.name;const date=Temporal.Now.plainDateISO('America/Guatemala').toString();
 async function post(path:string,data:Record<string,unknown>){const response=await page.request.post(path,{headers:{Origin:'http://localhost:3100'},data:{academy:scope.academy,branch:scope.branch,data,key:crypto.randomUUID()}});const result=await response.json();expect(result.error).toBeUndefined();expect(response.ok()).toBeTruthy();return result.id as string;}
 const product=await post('/api/data/products',{name:`Gi ${suffix}`,kind:'venta',active:true});const variant=await post('/api/data/product_variants',{product_id:product,name:`Azul ${suffix}`,code:`GI-${suffix}`,unit:'unidad',price:'50.00',min_stock:'1',active:true});
 const cash=await post('/api/data/accounts',{name:`Caja ${suffix}`,kind:'recepcion',active:true});await post('/api/operations/open_cash',{account_id:cash,opening_amount:'100.00'});await post('/api/operations/inventory_adjustment',{variant_id:variant,quantity:'3',unit_cost:'20.00',reason:'Fondo de pruebas'});
 await page.goto(`/panel/ventas?academy=${scope.academy}&branch=${scope.branch}`);await page.getByRole('combobox',{name:'Elegir acción'}).selectOption('sale');let dialog=page.getByRole('dialog');await dialog.getByLabel('Cliente externo',{exact:true}).fill(`Cliente ${suffix}`);await dialog.getByRole('button',{name:'Agregar línea'}).nth(1).click();
 const productOption=dialog.getByRole('combobox',{name:'Producto o servicio',exact:true}).getByRole('option',{name:new RegExp(`Azul ${suffix}`)});await expect(productOption).toHaveCount(1);await dialog.getByRole('combobox',{name:'Producto o servicio',exact:true}).selectOption((await productOption.getAttribute('value'))!);await dialog.getByLabel('Cantidad',{exact:true}).fill('1');
 await dialog.getByRole('button',{name:'Agregar línea'}).last().click();await dialog.getByRole('combobox',{name:'Caja o cuenta',exact:true}).selectOption({label:`Caja ${suffix}`});await dialog.getByRole('combobox',{name:'Medio de pago',exact:true}).selectOption({label:'Efectivo'});await dialog.getByLabel('Importe retenido',{exact:true}).fill('50.00');await dialog.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('cell',{name:`Cliente ${suffix}`,exact:true})).toBeVisible();
 const category=await post('/api/data/expense_categories',{name:`Servicios ${suffix}`,active:true});const expense=await post('/api/operations/expense',{description:`Luz ${suffix}`,category_id:category,amount:'10.00',incurred_on:date,due_on:date});await post('/api/operations/approve_expense',{expense_id:expense});
 await page.goto(`/panel/gastos?academy=${scope.academy}&branch=${scope.branch}`);await page.getByRole('combobox',{name:'Elegir acción'}).selectOption('pay_expense');dialog=page.getByRole('dialog');const obligation=dialog.getByRole('combobox',{name:'Obligación',exact:true}).getByRole('option',{name:new RegExp(`Luz ${suffix}`)});await expect(obligation).toHaveCount(1);await dialog.getByRole('combobox',{name:'Obligación',exact:true}).selectOption(expense);await dialog.getByRole('combobox',{name:'Caja o cuenta',exact:true}).selectOption(cash);await dialog.getByLabel('Importe a pagar',{exact:true}).fill('10.00');await dialog.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(dialog).not.toBeVisible();
 const sessions=await (await page.request.get(`/api/data/cash_sessions?academy=${scope.academy}&branch=${scope.branch}`)).json();const session=sessions.rows.find((r:{account_id:string})=>r.account_id===cash);
 await page.goto(`/panel/cajas?academy=${scope.academy}&branch=${scope.branch}&tab=cash_sessions`);await page.getByRole('combobox',{name:'Elegir acción'}).selectOption('close_cash');dialog=page.getByRole('dialog');await expect(dialog.getByRole('combobox',{name:'Sesión abierta',exact:true}).getByRole('option',{name:new RegExp(`Caja ${suffix}`)})).toHaveCount(1);await dialog.getByRole('combobox',{name:'Sesión abierta',exact:true}).selectOption(session.id);await dialog.getByLabel('Importe contado',{exact:true}).fill('140.00');await dialog.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('cell',{name:'140,00 USD'}).first()).toBeVisible();
 const room=await post('/api/data/rooms',{name:`Tatami ${suffix}`,capacity:'3',active:true});const discipline=await post('/api/data/disciplines',{name:`Jiu jitsu ${suffix}`,active:true});const instructor=await post('/api/data/employees',{name:`Instructor ${suffix}`,position:'Instructor',status:'activo'});
 await page.goto(`/panel/calendario?academy=${scope.academy}&branch=${scope.branch}`);await page.getByRole('combobox',{name:'Elegir acción'}).selectOption('class');dialog=page.getByRole('dialog');await dialog.getByLabel('Clase',{exact:true}).fill(`Clase ${suffix}`);await expect(dialog.getByRole('combobox',{name:'Instructor',exact:true}).getByRole('option',{name:`Instructor ${suffix}`})).toHaveCount(1);await dialog.getByRole('combobox',{name:'Instructor',exact:true}).selectOption(instructor);await dialog.getByRole('combobox',{name:'Disciplina',exact:true}).selectOption(discipline);await dialog.getByRole('combobox',{name:'Espacio',exact:true}).selectOption(room);await dialog.getByLabel('Inicio',{exact:true}).fill(`${date}T18:00`);await dialog.getByLabel('Fin',{exact:true}).fill(`${date}T19:00`);await dialog.getByLabel('Capacidad',{exact:true}).fill('3');await dialog.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(dialog).not.toBeVisible();
 await page.getByRole('combobox',{name:'Elegir acción'}).selectOption('attendance');dialog=page.getByRole('dialog');await expect(dialog.getByRole('combobox',{name:'Clase',exact:true}).getByRole('option',{name:`Clase ${suffix}`})).toHaveCount(1);await dialog.getByRole('combobox',{name:'Clase',exact:true}).selectOption({label:`Clase ${suffix}`});await dialog.getByRole('combobox',{name:'Estudiante',exact:true}).selectOption(scope.student);await dialog.getByLabel('Motivo de excepción',{exact:true}).fill('Prueba autorizada de interfaz');await dialog.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(dialog).not.toBeVisible();await page.getByRole('tab',{name:'Asistencia',exact:true}).click();await expect(page.getByRole('cell',{name:`Clase ${suffix}`,exact:true})).toBeVisible();
 await page.screenshot({path:`test-results/${suffix}-attendance.png`,fullPage:true});
});
