import { test,expect,type Page } from '@playwright/test';
async function admin(page:Page){await page.goto('/login');await page.getByLabel('Correo electrónico').fill('admin@test.invalid');await page.getByLabel('Contraseña',{exact:true}).fill('test-only-password-123');await page.getByRole('button',{name:'Entrar a la academia'}).click();await expect(page).toHaveURL(/superadmin\/mfa/);const before=await page.request.get('/api/platform/businesses');expect(before.status()).toBe(403);await page.getByLabel('Código de seis dígitos').fill('111111');await page.getByRole('button',{name:'Verificar y entrar'}).click();await expect(page.getByRole('heading',{name:'Tu plataforma, en perspectiva'})).toBeVisible();}
test('alta con MFA, contrato, invitación existente, pago parcial y comprobante',async({page,browser},info)=>{
 test.setTimeout(120000);await admin(page);
 await page.goto('/superadmin/planes');await page.getByRole('button',{name:'Crear plan',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Nombre del plan').fill(`Comercial ${info.project.name}`);await dialog.getByLabel('Descripción',{exact:true}).fill('Solo datos de prueba aislados');await dialog.getByLabel('Precio contratado').fill('100');await dialog.getByLabel('Límite de sucursales',{exact:true}).fill('2');await dialog.getByLabel('Límite de usuarios internos',{exact:true}).fill('4');await dialog.getByLabel('Moneda del plan').fill('USD');await dialog.getByLabel('Ciclo de cobro',{exact:true}).selectOption('mensual');await dialog.getByLabel('Inventario y compras',{exact:true}).check();await dialog.getByLabel('Punto de venta',{exact:true}).check();await dialog.getByRole('button',{name:'Confirmar y guardar'}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('cell',{name:`Comercial ${info.project.name}`,exact:true})).toBeVisible();
 await page.goto('/superadmin/ajustes');await page.getByRole('button',{name:'Crear medio de pago'}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Nombre del medio').fill(`Efectivo ${info.project.name}`);await dialog.getByLabel('Tipo',{exact:true}).selectOption('efectivo');await dialog.getByRole('button',{name:'Confirmar y guardar'}).click();await expect(dialog).not.toBeVisible();
 await page.goto('/superadmin/negocios');await page.getByRole('button',{name:'Nuevo negocio'}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Nombre comercial',{exact:true}).fill(`Academia ${info.project.name}`);await dialog.getByLabel('Responsable comercial',{exact:true}).fill('Responsable de prueba');await dialog.getByRole('button',{name:'Continuar'}).click();await dialog.getByLabel('Nombre del propietario').fill('Propietario de prueba');await dialog.getByLabel('Correo del propietario').fill('owner@test.invalid');await dialog.getByRole('button',{name:'Continuar'}).click();await dialog.getByLabel('País',{exact:true}).fill('Nicaragua');await dialog.getByLabel('Moneda operativa').fill('NIO');await dialog.getByRole('button',{name:'Continuar'}).click();await dialog.getByLabel('Nombre de la sucursal inicial').fill('Central');await dialog.getByRole('button',{name:'Continuar'}).click();await dialog.getByLabel('Plan comercial',{exact:true}).selectOption({label:`Comercial ${info.project.name}`});await dialog.getByRole('button',{name:'Continuar'}).click();await dialog.getByRole('button',{name:'Continuar'}).click();await dialog.getByLabel('Revisé los datos y autorizo el alta.').check();await dialog.getByRole('button',{name:'Confirmar y guardar'}).click();await expect(page).toHaveURL(/superadmin\/negocios\/[a-f0-9-]+/);await expect(page.getByText('Cuenta existente vinculada. Conserva sus otros accesos.')).toBeVisible();await expect(page.getByText('Invitación: vinculada')).toBeVisible();
 const businessId=page.url().split('/').pop()!.split('?')[0];
 await page.getByRole('button',{name:'Registrar pago de suscripción',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Medio de pago',{exact:true}).selectOption({label:`Efectivo ${info.project.name}`});await dialog.getByLabel('Importe total',{exact:true}).fill('40');await dialog.getByLabel('Moneda del pago').fill('USD');await dialog.getByLabel('Cargo',{exact:true}).selectOption({index:1});await dialog.getByLabel('Importe aplicado',{exact:true}).fill('40');await dialog.getByRole('button',{name:'Confirmar y guardar'}).click();await expect(dialog).not.toBeVisible();await expect(page.getByText(/60,00.*USD/).first()).toBeVisible();await page.getByRole('tab',{name:'Pagos de plataforma'}).click();await expect(page.getByRole('cell',{name:'confirmado',exact:true})).toBeVisible();
 const receipt=page.getByRole('link',{name:'Comprobante',exact:true}).first();const response=await page.request.get((await receipt.getAttribute('href'))!);expect(response.ok()).toBe(true);expect(await response.text()).toContain('Comprobante administrativo');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/${info.project.name}-platform-business.png`,fullPage:true});
 const ownerContext=await browser.newContext({viewport:page.viewportSize()??undefined});const ownerPage=await ownerContext.newPage();await ownerPage.goto('http://localhost:3100/login');await ownerPage.getByLabel('Correo electrónico').fill('owner@test.invalid');await ownerPage.getByLabel('Contraseña',{exact:true}).fill('test-only-password-123');await ownerPage.getByRole('button',{name:'Entrar a la academia'}).click();await expect(ownerPage.getByRole('heading',{name:'Hola, Propietario'})).toBeVisible();
 await page.getByRole('button',{name:'Suspender acceso',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Motivo',{exact:true}).fill('Suspensión administrativa en pruebas');await dialog.getByLabel('Observación interna').fill('No visible para el negocio');await dialog.getByLabel('Confirmo esta operación y sus condiciones.').check();await dialog.getByRole('button',{name:'Confirmar y guardar'}).click();await expect(dialog).not.toBeVisible();await expect(page.getByText('Suspendida manualmente',{exact:true})).toBeVisible();
 await ownerPage.goto(`http://localhost:3100/panel/estudiantes?academy=${businessId}`);await expect(ownerPage).toHaveURL(/\/servicio\?/);await expect(ownerPage.getByRole('heading',{name:'El acceso está suspendido'})).toBeVisible();const direct=await ownerPage.request.get(`http://localhost:3100/api/data/students?academy=${businessId}`);expect(direct.status()).toBe(403);const report=await ownerPage.request.get(`http://localhost:3100/api/data/students?academy=${businessId}&export=csv`);expect(report.status()).toBe(403);const doc=await ownerPage.request.get(`http://localhost:3100/api/documents/${crypto.randomUUID()}?academy=${businessId}`);expect(doc.status()).toBe(403);const denied=await ownerPage.request.get('http://localhost:3100/api/platform/plans');expect(denied.status()).toBe(403);await ownerPage.goto('http://localhost:3100/superadmin');await expect(ownerPage.getByRole('heading',{name:'Acceso de plataforma restringido'})).toBeVisible();await ownerPage.goto(`http://localhost:3100/servicio?academy=${businessId}`);await ownerPage.screenshot({path:`test-results/${info.project.name}-service-suspended.png`,fullPage:true});await ownerContext.close();
});
test('invitación fallida se reintenta sin duplicar negocio ni contrato',async({page},info)=>{
 await admin(page);const plans=await (await page.request.get('/api/platform/plans')).json();const plan=plans.rows.find((p:{name:string})=>p.name===`Comercial ${info.project.name}`);expect(plan).toBeTruthy();const today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Managua'});const key=crypto.randomUUID(),body={name:`Reintento ${info.project.name}`,country:'Nicaragua',currency:'NIO',timezone:'America/Managua',responsible_name:'Responsable',owner_name:'Propietario',owner_email:`fallo-${info.project.name}@test.invalid`,branch_name:'Única',plan_id:plan.id,starts_on:today,trial_days:10};const post=(action:string,data:Record<string,unknown>,operationKey=crypto.randomUUID())=>page.request.post(`/api/platform/${action}`,{headers:{Origin:'http://localhost:3100'},data:{key:operationKey,data}});
 const first=await post('create_business',body,key);expect(first.ok()).toBe(true);const id=(await first.json()).id;expect((await (await post('create_business',body,key)).json()).id).toBe(id);const failed=await post('invite',{academy_id:id,reason:'Intento con SMTP simulado fallido'});expect((await failed.json()).status).toBe('fallida');await page.goto(`/superadmin/negocios/${id}`);await expect(page.getByText('Invitación: fallida')).toBeVisible();await page.getByRole('button',{name:'Invitar o vincular al propietario'}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Motivo',{exact:true}).fill('Reintento después de reparar SMTP');await dialog.getByRole('button',{name:'Confirmar y guardar'}).click();await expect(dialog).not.toBeVisible();await expect(page.getByText('Invitación: enviada')).toBeVisible();const list=await (await page.request.get(`/api/platform/businesses?academy_id=${id}`)).json();expect(list.count).toBe(1);expect(list.rows[0].invitation_attempts).toBe(2);
});
test('archivos privados pasan por proxy autorizado y bloquean enlaces directos',async({page},info)=>{
 await admin(page);const businesses=await (await page.request.get('/api/platform/businesses')).json();const business=businesses.rows.find((b:{commercial_name:string})=>b.commercial_name===`Reintento ${info.project.name}`);expect(business).toBeTruthy();
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aY9kAAAAASUVORK5CYII=','base64');
 const uploaded=await page.request.post('/api/platform-files',{headers:{Origin:'http://localhost:3100'},multipart:{academy_id:business.id,kind:'logo',title:'Logo de prueba',key:crypto.randomUUID(),file:{name:'logo.png',mimeType:'image/png',buffer:png}}});const d=await uploaded.json();expect(d.error).toBeUndefined();expect(uploaded.ok()).toBe(true);
 const proxy=await page.request.get(`/api/platform-files?id=${d.id}`);expect(proxy.ok()).toBe(true);expect(proxy.headers()['cache-control']).toContain('no-store');expect(proxy.headers()['content-type']).toBe('image/png');expect(await proxy.body()).toEqual(png);
 const login=await page.request.post('http://127.0.0.1:54321/auth/v1/token?grant_type=password',{data:{email:'admin@test.invalid',password:'test-only-password-123'}});const session=await login.json();const docs=await (await page.request.get(`/api/platform/documents?academy_id=${business.id}`)).json();const path=docs.rows.find((doc:{id:string})=>doc.id===d.id).path;
 const direct=await page.request.post(`http://127.0.0.1:54321/storage/v1/object/sign/platform-private/${path}`,{headers:{Authorization:`Bearer ${session.access_token}`},data:{expiresIn:3600}});expect(direct.status()).toBe(403);
 await page.goto('/login');await page.getByLabel('Correo electrónico').fill('owner@test.invalid');await page.getByLabel('Contraseña',{exact:true}).fill('test-only-password-123');await page.getByRole('button',{name:'Entrar a la academia'}).click();await expect(page.getByRole('heading',{name:'Hola, Propietario'})).toBeVisible();
 const scope=await (await page.request.get('http://127.0.0.1:54321/test/context')).json();const academyUpload=await page.request.post('/api/documents',{headers:{Origin:'http://localhost:3100'},multipart:{academy:scope.academy,branch:scope.branch,title:'Documento privado de prueba',student_id:scope.student,file:{name:'documento.png',mimeType:'image/png',buffer:png}}});const privateDoc=await academyUpload.json();expect(privateDoc.error).toBeUndefined();expect(academyUpload.ok()).toBe(true);const academyDownload=await page.request.get(`/api/documents/${privateDoc.id}?academy=${scope.academy}`);expect(academyDownload.ok()).toBe(true);expect(await academyDownload.body()).toEqual(png);
 const ownerLogin=await page.request.post('http://127.0.0.1:54321/auth/v1/token?grant_type=password',{data:{email:'owner@test.invalid',password:'test-only-password-123'}});const ownerSession=await ownerLogin.json();
 for(const forgedPath of [`${business.id}/${crypto.randomUUID()}/${crypto.randomUUID()}.png`,`${scope.academy}/${crypto.randomUUID()}/${crypto.randomUUID()}.png`]){
  const seed=await page.request.post(`http://127.0.0.1:54321/storage/v1/object/academy-private/${forgedPath}`,{headers:{Authorization:'Bearer test-only-admin','Content-Type':'image/png'},data:png});expect(seed.ok()).toBe(true);
  const forged=await page.request.patch(`http://127.0.0.1:54321/rest/v1/documents?id=eq.${privateDoc.id}`,{headers:{Authorization:`Bearer ${ownerSession.access_token}`},data:{path:forgedPath}});expect(forged.ok()).toBe(true);
  const blocked=await page.request.get(`/api/documents/${privateDoc.id}?academy=${scope.academy}`);expect(blocked.status()).toBe(403);
 }
 await admin(page);const studentDenied=await page.request.get(`/api/documents/${privateDoc.id}?academy=${scope.academy}`);expect(studentDenied.status()).toBe(403);
});
