import { beforeAll,afterAll,it,expect } from 'vitest';
import { database,identity,rpc } from './db-harness';
import type { PGlite } from '@electric-sql/pglite';
let db:PGlite,plan:string,a:string,b:string,cash:string,transfer:string,branch:string;const admin=crypto.randomUUID(),owner=crypto.randomUUID(),other=crypto.randomUUID();
async function superadmin(aal='aal2'){await identity(db,admin);await db.query("select set_config('request.jwt.claim.aal',$1,false)",[aal]);}
async function operate(action:string,data:Record<string,unknown>,key=crypto.randomUUID()){return(await db.query<{result:Record<string,unknown>}>('select public.platform_operate($1,$2::jsonb,$3) result',[action,JSON.stringify(data),key])).rows[0].result;}
async function data(resource:string,filters:Record<string,unknown>={}){return(await db.query<{result:Record<string,unknown>}>('select public.platform_data($1,$2::jsonb) result',[resource,JSON.stringify(filters)])).rows[0].result;}
async function bind(academy:string,user:string,email:string){await superadmin();const claim=await operate('invite_claim',{academy_id:academy,reason:'Vincular propietario autorizado'});await db.exec('reset role');await db.query('select public.platform_finish_invitation($1,$2,$3,$4,null)',[academy,claim.token,user,'vinculada']);expect(email).toContain('@');}
beforeAll(async()=>{
 db=await database();for(const [id,email] of [[admin,'admin@test.invalid'],[owner,'platform-owner@test.invalid'],[other,'other-owner@test.invalid']])await db.query('insert into auth.users(id,email) values($1,$2)',[id,email]);
 await db.query("select public.bootstrap_superadmin($1,'Nombramiento por consola de prueba')",[admin]);await db.query("insert into auth.mfa_factors(user_id,status) values($1,'verified')",[admin]);await superadmin();
 plan=(await operate('plan',{name:'Plan de prueba',description:'Ficticio',price:'100.00',currency:'USD',cycle:'mensual',trial_days:0,max_branches:3,max_users:5,max_students:5,modules:['sales','inventory','classes','staff','reports'],active:true})).id as string;
 cash=(await operate('payment_method',{name:'Efectivo de prueba',kind:'efectivo',requires_verification:false,active:true})).id as string;
 transfer=(await operate('payment_method',{name:'Transferencia de prueba',kind:'transferencia',requires_verification:true,active:true})).id as string;
 const today=(await db.query<{day:string}>('select current_date::text as day')).rows[0].day;
 const business={name:'Negocio uno',country:'Prueba',currency:'NIO',timezone:'America/Managua',responsible_name:'Responsable',owner_name:'Propietario',owner_email:'platform-owner@test.invalid',branch_name:'Central',plan_id:plan,starts_on:today,trial_days:0};
 a=(await operate('create_business',business)).id as string;b=(await operate('create_business',{...business,name:'Negocio dos',owner_email:'other-owner@test.invalid'})).id as string;
 await bind(a,owner,'platform-owner@test.invalid');await bind(b,other,'other-owner@test.invalid');await identity(db,owner);branch=(await db.query<{id:string}>('select id from public.branches where academy_id=$1',[a])).rows[0].id;await superadmin();
});
afterAll(async()=>{await db?.close();});
async function newBusiness(name:string,currency='USD'){
 await superadmin();const today=(await db.query<{d:string}>('select current_date::text d')).rows[0].d;
 return (await operate('create_business',{name,country:'Prueba',currency,timezone:'UTC',responsible_name:'Responsable',owner_name:'Propietario',owner_email:'platform-owner@test.invalid',branch_name:'Central',plan_id:plan,starts_on:today,trial_days:0})).id as string;
}
it('alta conserva negocio y permite recuperar una invitación fallida sin duplicación',async()=>{
 const today=(await db.query<{d:string}>('select current_date::text d')).rows[0].d;const payload={name:'Alta reintentable',country:'Prueba',currency:'USD',timezone:'UTC',responsible_name:'Responsable',owner_name:'Otro',owner_email:'pending@test.invalid',branch_name:'Única',plan_id:plan,starts_on:today,trial_days:14};const key=crypto.randomUUID();
 const first=await operate('create_business',payload,key);expect(await operate('create_business',payload,key)).toEqual(first);
 const claim=await operate('invite_claim',{academy_id:first.id,reason:'Intento inicial autorizado'});await db.exec('reset role');await db.query("select public.platform_finish_invitation($1,$2,null,'fallida','SMTP de prueba no disponible')",[first.id,claim.token]);await superadmin();
 const retry=await operate('invite_claim',{academy_id:first.id,reason:'Reintentar después del fallo'});expect(retry.token).not.toBe(claim.token);const businesses=await data('businesses',{academy_id:first.id});expect(businesses.count).toBe(1);expect((businesses.rows as Record<string,unknown>[])[0].invitation_attempts).toBe(2);
 await expect(operate('invite_claim',{academy_id:first.id,reason:'Segundo clic concurrente'})).rejects.toThrow('curso');
});
it('academias no acceden a plataforma ni cambian plan o estado; Superadmin no obtiene expedientes',async()=>{
 await identity(db,owner);await expect(data('businesses')).rejects.toThrow('multifactor');expect((await db.query('select * from public.platform_plans')).rows).toHaveLength(0);
 await expect(db.query('update public.platform_subscriptions set manual_block=false where academy_id=$1',[a])).rejects.toThrow('permission');
 await expect(db.query("insert into private.platform_admins(user_id,reason) values($1,'Autopromoción')",[owner])).rejects.toThrow('permission');
 const student=(await db.query<{id:string}>("insert into public.students(academy_id,branch_id,name,joined_on) values($1,$2,'Privado',current_date) returning id",[a,branch])).rows[0].id;expect(student).toBeTruthy();await superadmin();expect((await db.query('select * from public.students')).rows).toHaveLength(0);
});
it('MFA se exige en RPC, RLS y Storage incluso al administrador registrado',async()=>{
 await superadmin('aal1');await expect(data('settings')).rejects.toThrow('multifactor');expect((await db.query('select * from public.platform_businesses')).rows).toHaveLength(0);expect((await db.query("select * from storage.objects where bucket_id='platform-private'")).rows).toHaveLength(0);
 await superadmin();expect((await data('businesses')).count).toBe(3);await db.exec('reset role');await db.query("update auth.mfa_factors set status='unverified' where user_id=$1",[admin]);await superadmin();await expect(data('businesses')).rejects.toThrow('multifactor');await db.exec('reset role');await db.query("update auth.mfa_factors set status='verified' where user_id=$1",[admin]);await superadmin();
});
it('pagos parciales y completos no se mezclan con mensualidades ni duplican aplicaciones',async()=>{
 const charge=(await data('charges',{academy_id:a})).rows as Record<string,unknown>[];const key=crypto.randomUUID();const payload={academy_id:a,method_id:cash,amount:'40.00',currency:'USD',applications:[{charge_id:charge[0].id,amount:'40.00'}]};const payment=await operate('payment',payload,key);expect(await operate('payment',payload,key)).toEqual(payment);
 expect(((await data('charges',{academy_id:a})).rows as Record<string,unknown>[])[0].balance).toBe(60);await operate('payment',{...payload,amount:'60.00',applications:[{charge_id:charge[0].id,amount:'60.00'}]});expect(((await data('charges',{academy_id:a})).rows as Record<string,unknown>[])[0].balance).toBe(0);
 expect((await db.query('select * from public.payments')).rows).toHaveLength(0);
});
it('transferencia pendiente no salda deuda; rechazo libera reserva y confirmación es idempotente',async()=>{
 const charge=((await data('charges',{academy_id:b})).rows as Record<string,unknown>[])[0];const payload={academy_id:b,method_id:transfer,amount:'100.00',currency:'USD',reference:'Referencia ficticia',applications:[{charge_id:charge.id,amount:'100.00'}]};
 const payment=await operate('payment',payload);expect(((await data('charges',{academy_id:b})).rows as Record<string,unknown>[])[0].balance).toBe(100);await expect(operate('payment',payload)).rejects.toThrow('saldo');await operate('reject_payment',{academy_id:b,payment_id:payment.id,reason:'Transferencia no recibida'});
 const second=await operate('payment',payload);await operate('confirm_payment',{academy_id:b,payment_id:second.id});await operate('confirm_payment',{academy_id:b,payment_id:second.id});expect(((await data('charges',{academy_id:b})).rows as Record<string,unknown>[])[0].balance).toBe(0);
});
it('recurrencia recupera meses omitidos y conserva cargos y contrato histórico',async()=>{
 await db.exec('reset role');await db.query("update public.platform_subscriptions set next_charge_on='2026-01-31',starts_on='2026-01-31',anchor_day=31 where academy_id=$1",[a]);await superadmin();await operate('generate',{academy_id:a,cutoff:'2026-03-31'});const before=(await data('charges',{academy_id:a})).count;
 await operate('generate',{academy_id:a,cutoff:'2026-03-31'});expect((await data('charges',{academy_id:a})).count).toBe(before);await operate('plan',{id:plan,name:'Plan cambiado',description:'Ficticio',price:'200.00',currency:'USD',cycle:'mensual',trial_days:0,max_branches:3,max_users:5,max_students:5,modules:['sales','inventory','classes','staff','reports'],active:true});
 expect(((await data('charges',{academy_id:a})).rows as Record<string,unknown>[]).every(c=>Number(c.amount)===100)).toBe(true);
});
it('suspensión revoca sesión vigente, llamadas directas, reportes y archivos; reactivar conserva datos',async()=>{
 await db.exec('reset role');await db.query("insert into storage.objects(bucket_id,name) values('academy-private',$1)",[`${a}/${branch}/privado.pdf`]);await superadmin();await operate('suspend',{academy_id:a,reason:'Suspensión administrativa de prueba',internal_note:'Observación secreta',customer_message:'Contacta a soporte'});
 await identity(db,owner);expect((await db.query('select * from public.students')).rows).toHaveLength(0);expect((await db.query("select * from storage.objects where bucket_id='academy-private'")).rows).toHaveLength(0);await expect(rpc(db,a,branch,'charge',{amount:'10.00',description:'Rechazada',due_on:'2026-10-07'})).rejects.toThrow('permiso');await expect(db.query("select public.dashboard($1,$2,'2026-01-01','2026-12-31')",[a,branch])).rejects.toThrow('permiso');
 const limited=(await db.query<{s:Record<string,unknown>}>('select public.academy_service($1) s',[a])).rows[0].s;expect(limited.operational).toBe(false);expect(limited.message).toBe('Contacta a soporte');expect(JSON.stringify(limited)).not.toContain('Observación secreta');
 await superadmin();await operate('reactivate',{academy_id:a,reason:'Reactivar después de revisión'});await identity(db,owner);expect((await db.query('select * from public.students')).rows).toHaveLength(1);await superadmin();
});
it('un pago no levanta suspensión manual y una extensión vence sin borrar bloqueos',async()=>{
 await operate('suspend',{academy_id:a,reason:'Bloqueo manual independiente'});const charges=((await data('charges',{academy_id:a})).rows as Record<string,unknown>[]).filter(c=>Number(c.balance)>0);const total=charges.reduce((sum,c)=>sum+Number(c.balance),0);await operate('payment',{academy_id:a,method_id:cash,amount:total.toFixed(2),currency:'USD',applications:charges.map(c=>({charge_id:c.id,amount:String(c.balance)}))});
 expect(((await data('businesses',{academy_id:a})).rows as Record<string,unknown>[])[0].access).toBe('suspendida_manual');await operate('reactivate',{academy_id:a,reason:'Levantamiento explícito del bloqueo'});
 await db.exec('reset role');await db.query("insert into public.platform_charges(academy_id,contract_id,description,amount,currency,period_on,due_on) select academy_id,contract_id,'Atraso de prueba',10,'USD','2025-12-01','2025-12-01' from public.platform_subscriptions where academy_id=$1",[a]);await superadmin();const preview=await data('preview');await operate('automation',{enabled:true,preview_token:preview.token,reason:'Activación expresa después de vista previa'});
 await operate('grace',{academy_id:a,grace_days:5,automatic_suspension:true,reason:'Tolerancia configurada de prueba'});const today=(await db.query<{d:string}>('select current_date::text d')).rows[0].d;await operate('extend',{academy_id:a,extension_until:today,reason:'Acceso temporal autorizado'});expect(((await data('businesses',{academy_id:a})).rows as Record<string,unknown>[])[0].access).toBe('extension_temporal');
 await db.exec('reset role');expect((await db.query<{s:string}>('select private.business_access($1,false,current_date+1) s',[a])).rows[0].s).toBe('suspendida_impago');await superadmin();
});
it('módulos y límites se aplican en DB sin borrar registros al bajar plan',async()=>{
 await expect(operate('assign_plan',{academy_id:b,plan_id:plan,modules:['sales'],reason:'Configuración incoherente'})).rejects.toThrow('check');
 await operate('assign_plan',{academy_id:b,plan_id:plan,modules:[],max_branches:1,max_users:1,max_students:1,reason:'Reducir límites conservando información'});
 await identity(db,other);await expect(db.query("insert into public.branches(academy_id,name) values($1,'Excede')",[b])).rejects.toThrow('límite');expect((await db.query('select * from public.branches where academy_id=$1',[b])).rows).toHaveLength(1);await expect(db.query("insert into public.products(academy_id,name) values($1,'Bloqueado')",[b])).rejects.toThrow('row-level');
 expect((await db.query('select * from public.students where academy_id=$1',[a])).rows).toHaveLength(0);await superadmin();await operate('assign_plan',{academy_id:b,plan_id:plan,reason:'Restaurar módulos y condiciones'});await identity(db,other);await db.query("insert into public.products(academy_id,name) values($1,'Permitido')",[b]);await superadmin();
});
it('pagos y ajustes rechazan mezclas de moneda, negocio y saldos negativos',async()=>{
 const charge=((await data('charges',{academy_id:a})).rows as Record<string,unknown>[]).find(c=>Number(c.balance)>0)!;
 await expect(operate('payment',{academy_id:b,method_id:cash,amount:'1.00',currency:'USD',applications:[{charge_id:charge.id,amount:'1.00'}]})).rejects.toThrow('otro negocio');
 await expect(operate('payment',{academy_id:a,method_id:cash,amount:'1.00',currency:'NIO',applications:[{charge_id:charge.id,amount:'1.00'}]})).rejects.toThrow('moneda');await expect(operate('adjustment',{academy_id:a,charge_id:charge.id,amount:'-100.00',reason:'Descuento superior a la deuda'})).rejects.toThrow('negativo');
});
it('la gracia considera el día exacto de vencimiento y su límite sin cobrar dos veces',async()=>{
 const id=await newBusiness('Gracia aislada');await operate('grace',{academy_id:id,grace_days:3,automatic_suspension:true,reason:'Tolerancia contractual verificada'});await db.exec('reset role');
 expect((await db.query<{s:string}>('select private.business_access($1,true,current_date+3) s',[id])).rows[0].s).toBe('gracia');
 expect((await db.query<{s:string}>('select private.business_access($1,true,current_date+4) s',[id])).rows[0].s).toBe('suspendida_impago');await superadmin();
});
it('cancelar conserva historial y detiene nuevos cargos de plataforma',async()=>{
 const id=await newBusiness('Cancelación aislada');const before=await data('charges',{academy_id:id});await operate('cancel',{academy_id:id,reason:'Cliente solicitó cancelar servicio',customer_message:'Servicio cancelado por solicitud'});await operate('generate',{academy_id:id,cutoff:'2030-12-31'});expect((await data('charges',{academy_id:id})).count).toBe(before.count);expect(((await data('businesses',{academy_id:id})).rows as Record<string,unknown>[])[0].access).toBe('cancelada');
});
it('empleados suspendidos no ven deuda, instrucciones ni notas comerciales privadas',async()=>{
 const employee=crypto.randomUUID();await db.exec('reset role');await db.query("insert into auth.users(id,email) values($1,'employee@test.invalid')",[employee]);const m=(await db.query<{id:string}>("insert into public.internal_members(academy_id,user_id,name,all_branches) values($1,$2,'Empleado',true) returning id",[b,employee])).rows[0].id;await db.query("insert into public.member_roles(academy_id,member_id,role_id) select $1,$2,id from public.roles where academy_id=$1 and name='Recepción/cajero'",[b,m]);await superadmin();await operate('suspend',{academy_id:b,reason:'Revisión administrativa interna',internal_note:'Solo plataforma',customer_message:'Cliente propietario'});await identity(db,employee);
 const limited=(await db.query<{s:Record<string,unknown>}>('select public.academy_service($1) s',[b])).rows[0].s;expect(limited.owner).toBe(false);expect(limited.balances).toBeUndefined();expect(limited.instructions).toBeUndefined();expect(limited.message).toContain('propietario');await superadmin();await operate('reactivate',{academy_id:b,reason:'Revisión completada del negocio'});
});
it('desactivar y volver a habilitar un módulo recupera sus datos y cambia los permisos',async()=>{
 await identity(db,other);const product=(await db.query<{id:string}>("insert into public.products(academy_id,name) values($1,'Producto conservado') returning id",[b])).rows[0].id;await superadmin();await operate('assign_plan',{academy_id:b,plan_id:plan,modules:[],reason:'Desactivar módulo conservando historial'});await identity(db,other);expect((await db.query('select id from public.products where id=$1',[product])).rows).toHaveLength(0);const disabled=(await db.query<{p:string[]}>('select public.my_permissions($1) p',[b])).rows[0].p;expect(disabled).not.toContain('inventory.read');expect(disabled).toContain('billing.read');await superadmin();await operate('assign_plan',{academy_id:b,plan_id:plan,reason:'Restaurar módulos contratados'});await identity(db,other);expect((await db.query('select id from public.products where id=$1',[product])).rows).toHaveLength(1);await superadmin();
});
it('límites de usuarios y estudiantes bloquean altas, conservan existentes y permiten actualizar propietario',async()=>{
 await operate('assign_plan',{academy_id:a,plan_id:plan,max_students:1,max_users:1,reason:'Plan reducido tras revisar uso actual'});await db.exec('reset role');await expect(db.query("insert into public.students(academy_id,branch_id,name,joined_on) values($1,$2,'Segundo',current_date)",[a,branch])).rejects.toThrow('límite');const another=crypto.randomUUID();await db.query("insert into auth.users(id,email) values($1,'extra@test.invalid')",[another]);await expect(db.query("insert into public.internal_members(academy_id,user_id,name) values($1,$2,'Extra')",[a,another])).rejects.toThrow('límite');await superadmin();const claim=await operate('invite_claim',{academy_id:a,resend:true,reason:'Revisar vinculación del propietario'});await db.exec('reset role');await db.query("select public.platform_finish_invitation($1,$2,$3,'vinculada',null)",[a,claim.token,owner]);await superadmin();expect(((await data('businesses',{academy_id:a})).rows as Record<string,unknown>[])[0].users_count).toBe(1);
});
it('trabajos operativos se pausan y requieren revisión después de reactivar; plataforma continúa',async()=>{
 await operate('suspend',{academy_id:a,reason:'Pausa de automatizaciones verificada'});await db.exec('reset role');const paused=(await db.query<{r:Record<string,unknown>[]}>('select public.scheduled_billing(100) r')).rows[0].r;expect(paused.some(r=>r.academy===a)).toBe(false);await superadmin();await operate('reactivate',{academy_id:a,reason:'Reanudación sujeta a revisión'});await db.exec('reset role');const waiting=(await db.query<{r:Record<string,unknown>[]}>('select public.scheduled_billing(100) r')).rows[0].r;expect(waiting.some(r=>r.academy===a)).toBe(false);await identity(db,owner);const recovery=(await db.query<{r:Record<string,unknown>}>('select public.academy_recovery($1) r',[a])).rows[0].r;expect(recovery.warning).toBeTruthy();const key=crypto.randomUUID();await db.query("select public.academy_resume($1,'Períodos revisados por propietario',$2)",[a,key]);await db.query("select public.academy_resume($1,'Períodos revisados por propietario',$2)",[a,key]);await db.exec('reset role');await expect(db.query('select public.scheduled_platform_billing(100)')).resolves.toBeTruthy();expect((await db.query<{recovery_required:boolean}>('select recovery_required from public.platform_subscriptions where academy_id=$1',[a])).rows[0].recovery_required).toBe(false);await superadmin();
});
it('sesiones de navegador no pueden generar enlaces reutilizables ni escribir Storage directamente',async()=>{
 await identity(db,owner);expect((await db.query('select * from storage.objects')).rows).toHaveLength(0);await expect(db.query("insert into storage.objects(bucket_id,name) values('academy-private',$1)",[`${a}/${branch}/directo.png`])).rejects.toThrow('row-level');await superadmin();expect((await db.query('select * from storage.objects')).rows).toHaveLength(0);
});
it('indicadores y listados monetarios mantienen NIO y USD separados',async()=>{
 await superadmin();const p=(await operate('plan',{name:'Plan NIO aislado',description:'Prueba',price:'10',currency:'NIO',cycle:'mensual',trial_days:0,max_branches:2,max_users:2,max_students:null,modules:[],active:true})).id;const today=(await db.query<{d:string}>('select current_date::text d')).rows[0].d;
 const id=(await operate('create_business',{name:'Moneda aislada',country:'Prueba',currency:'NIO',timezone:'UTC',responsible_name:'Responsable',owner_name:'Propietario',owner_email:'platform-owner@test.invalid',branch_name:'Central',plan_id:p,starts_on:today,trial_days:0})).id;
 const charge=((await data('charges',{academy_id:id})).rows as Record<string,unknown>[])[0];await operate('payment',{academy_id:id,method_id:cash,amount:'10',currency:'NIO',applications:[{charge_id:charge.id,amount:'10'}]});const metrics=await data('dashboard');const currencies=metrics.currencies as Record<string,unknown>[];expect(currencies.find(c=>c.currency==='NIO')?.collected).toBe('10.00');expect(currencies.find(c=>c.currency==='USD')).toBeTruthy();const nio=(await data('payments',{currency:'NIO'})).rows as Record<string,unknown>[];expect(nio.every(p=>p.currency==='NIO')).toBe(true);expect(nio).toHaveLength(1);
});
