'use client';
import { useEffect,useState } from 'react';
import { Temporal } from '@js-temporal/polyfill';
import { ChevronLeft,ChevronRight } from 'lucide-react';
import type { AppContext } from '@/lib/context';
type ClassRow={id:string;name:string;starts_at:string;ends_at:string;capacity:number;status:string;level:string|null;age_group:string|null;_labels?:Record<string,string>};
export function CalendarView({context,revision}:{context:AppContext;revision:number}){
 const [mode,setMode]=useState('semana'),[anchor,setAnchor]=useState(()=>Temporal.Now.plainDateISO(context.academy.timezone).toString()),[rows,setRows]=useState<ClassRow[]>([]),[error,setError]=useState('');
 const date=Temporal.PlainDate.from(anchor);const first=mode==='mes'?date.with({day:1}):mode==='semana'?date.subtract({days:date.dayOfWeek-1}):date;const days=mode==='mes'?date.daysInMonth:mode==='semana'?7:1;const start=first.toString(),end=first.add({days:days-1}).toString();
 useEffect(()=>{const controller=new AbortController();const query=new URLSearchParams({academy:context.academy.id,branch:context.branch??'all',from:start,to:end});async function load(){const all:ClassRow[]=[];for(let page=0;page<200;page++){query.set('page',String(page));const result=await(await fetch(`/api/data/classes?${query}`,{signal:controller.signal})).json();if(result.error)throw Error(result.error);all.push(...result.rows);if(all.length>=result.count)break;if(page===199)throw Error('Más de 10 000 clases. Reduce el período o consulta la lista paginada.');}setRows(all);setError('');}load().catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[context.academy.id,context.branch,start,end,revision]);
 const move=(direction:number)=>setAnchor(date.add(mode==='mes'?{months:direction}:{days:direction*days}).toString());
 return <section className="card calendar-card"><div className="calendar-toolbar"><div><button className="icon-btn" aria-label="Período anterior" onClick={()=>move(-1)}><ChevronLeft size={18}/></button><strong>{new Intl.DateTimeFormat(context.academy.locale,{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${anchor}T12:00:00Z`))}</strong><button className="icon-btn" aria-label="Período siguiente" onClick={()=>move(1)}><ChevronRight size={18}/></button></div><div><button className="btn small" onClick={()=>setAnchor(Temporal.Now.plainDateISO(context.academy.timezone).toString())}>Hoy</button><select aria-label="Vista de calendario" value={mode} onChange={e=>setMode(e.target.value)}><option value="dia">Día</option><option value="semana">Semana</option><option value="mes">Mes</option></select></div></div>{error&&<div className="notice">{error}</div>}<div className={`calendar-grid ${mode}`}>{Array.from({length:days},(_,index)=>{const day=first.add({days:index}).toString();const matches=rows.filter(row=>Temporal.Instant.from(row.starts_at).toZonedDateTimeISO(context.academy.timezone).toPlainDate().toString()===day);return <div className="calendar-day" key={day}><div className="day-title"><span>{new Intl.DateTimeFormat(context.academy.locale,{weekday:'short',timeZone:'UTC'}).format(new Date(`${day}T12:00:00Z`))}</span><strong>{day.slice(8)}</strong></div>{matches.map(row=><div className={`class-event ${row.status}`} key={row.id}><small>{new Intl.DateTimeFormat(context.academy.locale,{hour:'2-digit',minute:'2-digit',timeZone:context.academy.timezone}).format(new Date(row.starts_at))}</small><strong>{row.name}</strong><span>{row._labels?.substitute_id??row._labels?.instructor_id??'Instructor'} · {row.capacity} cupos</span>{(row.level||row.age_group)&&<span>{[row.level,row.age_group].filter(Boolean).join(" · ")}</span>}<small>{row.status}</small></div>)}</div>;})}</div></section>;
}
