'use client';
import { useEffect,useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { safeError } from '@/lib/validation';
export function PlatformMfa(){
 const [client]=useState(()=>createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!));
 const [factor,setFactor]=useState(''),[qr,setQr]=useState(''),[secret,setSecret]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);const router=useRouter();
 useEffect(()=>{let active=true;client.auth.mfa.listFactors().then(({data,error})=>{if(error)throw error;if(active){setFactor(data.totp.find(f=>f.status==='verified')?.id??'');setReady(true);}}).catch(e=>{if(active)setError(safeError(e));});return()=>{active=false;};},[client]);
 async function enroll(){setBusy(true);setError('');try{const listed=await client.auth.mfa.listFactors();if(listed.error)throw listed.error;for(const f of listed.data.all.filter(f=>f.status==='unverified')){const removed=await client.auth.mfa.unenroll({factorId:f.id});if(removed.error)throw removed.error;}const r=await client.auth.mfa.enroll({factorType:'totp',friendlyName:'Administración de plataforma',issuer:'Sistema Academia'});if(r.error)throw r.error;setFactor(r.data.id);setQr(r.data.totp.qr_code);setSecret(r.data.totp.secret);}catch(e){setError(safeError(e));}finally{setBusy(false);}}
 async function verify(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const challenge=await client.auth.mfa.challenge({factorId:factor});if(challenge.error)throw challenge.error;const result=await client.auth.mfa.verify({factorId:factor,challengeId:challenge.data.id,code});if(result.error)throw result.error;setSecret('');setQr('');router.replace('/superadmin');router.refresh();}catch{setError('No se pudo verificar. Comprueba el código y la hora de tu dispositivo.');}finally{setBusy(false);}}
 return <section className="card platform-security"><span className="eyebrow">ACCESO DE PLATAFORMA</span><h1>Verificación en dos pasos</h1><p>El panel requiere un código de tu aplicación autenticadora en cada sesión que necesite verificación.</p>{error&&<div className="error" role="alert">{error}{!ready&&<button className="btn small" onClick={()=>window.location.reload()}>Reintentar verificación</button>}</div>}{!ready?<p>{error?'Reintenta para consultar tus métodos de verificación.':'Cargando métodos de verificación…'}</p>:!factor?<button className="btn primary" onClick={enroll} disabled={busy}>Configurar aplicación autenticadora</button>:<>{qr&&<><Image src={qr.startsWith('data:')?qr:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(qr)}`} alt="Código QR para configurar la aplicación autenticadora" width={220} height={220} unoptimized/><details><summary>Usar clave manual</summary><code>{secret}</code></details><p>Guarda tu acceso a la aplicación autenticadora. La recuperación requiere al operador autorizado de Supabase.</p></>}<form onSubmit={verify} className="auth-form"><label>Código de seis dígitos<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} required value={code} onChange={e=>setCode(e.target.value)}/></label><button className="btn primary" disabled={busy}>{busy?'Verificando…':'Verificar y entrar'}</button></form></>}</section>;
}
