'use client';
import { useRef,useState } from 'react';
import { moduleNames,optionalModules,platformValues } from '@/domains/platform';
import { safeError } from '@/lib/validation';
import { formatMoney } from '@/lib/money';
export type PlatformRow=Record<string,unknown>;
type Field={key:string;label:string;type?:string;required?:boolean;options?:{id:string;name:string}[];min?:number;max?:number};
const field=(key:string,label:string,type='text',required=true):Field=>({key,label,type,required});
const why=field('reason','Motivo','textarea'),start=field('starts_on','Fecha de inicio','date');
const terms=[field('price','Precio contratado','number'),field('trial_days','Días de prueba','number'),field('max_branches','Límite de sucursales','number'),field('max_users','Límite de usuarios internos','number'),field('max_students','Límite de estudiantes activos (vacío: sin límite)','number',false),field('modules','Módulos incluidos','modules')];
export const actionNames:Record<string,string>={plan:'Guardar plan comercial',payment_method:'Guardar medio de pago',settings:'Guardar configuración',automation:'Cambiar suspensión automática',create_business:'Crear negocio',edit_business:'Actualizar datos comerciales',assign_plan:'Cambiar condiciones del contrato',trial:'Configurar período de prueba',extend:'Conceder extensión temporal',grace:'Configurar días de gracia',suspend:'Suspender acceso',reactivate:'Reactivar acceso',cancel:'Cancelar servicio',generate:'Generar cargos pendientes',generate_all:'Generar suscripciones pendientes',adjustment:'Registrar ajuste autorizado',payment:'Registrar pago de suscripción',confirm_payment:'Confirmar pago recibido',reject_payment:'Rechazar transferencia',invite:'Invitar o vincular al propietario'};
export function PlatformForm({action,academyId,initial={},plans,methods,charges,documents,preview,onClose,onSaved}:{action:string;academyId?:string;initial?:PlatformRow;plans:PlatformRow[];methods:PlatformRow[];charges:PlatformRow[];documents:PlatformRow[];preview?:PlatformRow;onClose:()=>void;onSaved:(result:PlatformRow)=>void}){
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Managua'});
 const choices=(rows:PlatformRow[],name='name')=>rows.map(r=>({id:String(r.id),name:String(r[name])}));
 const planField={...field('plan_id','Plan comercial','select'),options:choices(plans.filter(p=>p.active))};
 const businessSteps=[
  [field('name','Nombre comercial'),field('responsible_name','Responsable comercial'),field('contact_email','Correo de contacto','email',false),field('phone','Teléfono','tel',false),field('contact','Contacto público','text',false)],
  [field('owner_name','Nombre del propietario'),field('owner_email','Correo del propietario','email')],
  [field('country','País'),field('currency','Moneda operativa (código ISO)'),field('timezone','Zona horaria IANA')],
  [field('branch_name','Nombre de la sucursal inicial'),field('branch_address','Dirección de la sucursal','text',false)],
  [planField],[start,field('trial_days','Días de prueba','number')],[],
 ];
 const config:Record<string,Field[]>={
  plan:[field('name','Nombre del plan'),field('description','Descripción','textarea',false),...terms,field('currency','Moneda del plan (código ISO)'),{...field('cycle','Ciclo de cobro','select'),options:choices([{id:'mensual',name:'Mensual'},{id:'anual',name:'Anual'}])},field('active','Plan activo','checkbox')],
  payment_method:[field('name','Nombre del medio'),{...field('kind','Tipo','select'),options:choices([{id:'efectivo',name:'Efectivo'},{id:'transferencia',name:'Transferencia'},{id:'otro',name:'Otro'}])},field('requires_verification','Requiere verificación','checkbox'),field('active','Activo','checkbox')],
  settings:[field('timezone','Zona horaria comercial IANA'),field('contact','Contacto de plataforma','textarea',false),field('payment_instructions','Instrucciones de pago','textarea',false)],
  automation:[field('enabled','Activar suspensión automática por impago','checkbox'),why],
  edit_business:[field('name','Nombre comercial'),field('responsible_name','Responsable comercial'),field('contact_email','Correo de contacto','email',false),field('phone','Teléfono','tel',false),why],
  assign_plan:[planField,...terms,start,why],trial:[field('trial_until','Último día excluido de la prueba','date'),why],extend:[field('extension_until','Acceso temporal hasta (inclusive)','date'),why],
  grace:[field('grace_days','Días de gracia','number'),field('automatic_suspension','Aplicar suspensión automática a este negocio','checkbox'),why],
  suspend:[why,field('internal_note','Observación interna','textarea',false),field('customer_message','Mensaje visible para el cliente','textarea')],
  reactivate:[field('extension_until','Extensión temporal hasta (opcional)','date',false),why],cancel:[why,field('customer_message','Mensaje visible para el cliente','textarea')],
  generate:[field('cutoff','Recuperar períodos hasta','date')],generate_all:[],
  adjustment:[{...field('charge_id','Cargo','select'),options:charges.map(c=>({id:String(c.id),name:`${c.due_on} · ${formatMoney(c.balance,String(c.currency))}`}))},field('amount','Ajuste: negativo descuenta; positivo agrega','number'),why],
  payment:[{...field('method_id','Medio de pago','select'),options:choices(methods.filter(m=>m.active))},field('amount','Importe total','number'),field('currency','Moneda del pago (código ISO)'),field('reference','Referencia','text',false),{...field('document_id','Comprobante guardado','select',false),options:choices(documents.filter(d=>d.kind==='comprobante'),'title')},field('applications','Aplicaciones a cargos','applications')],
  confirm_payment:[],reject_payment:[why],invite:[field('resend','Reenviar invitación si ya fue enviada','checkbox'),why],
 };
 const fields=action==='create_business'?businessSteps.flat():config[action]??[];
 const defaults:PlatformRow={active:true,requires_verification:false,automatic_suspension:true,enabled:false,trial_days:0,grace_days:0,timezone:'America/Managua',starts_on:today,cutoff:today,modules:[],applications:[{charge_id:'',amount:''}],customer_message:'Contacta a la plataforma para revisar el servicio.',...initial};
 const [values,setValues]=useState<PlatformRow>(()=>Object.fromEntries([...fields.map(f=>[f.key,defaults[f.key]??'']),...(action==='plan'||action==='payment_method'?['id']:['confirm_payment','reject_payment'].includes(action)?['payment_id']:[]).filter(k=>initial[k]).map(k=>[k,initial[k]])]));
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[step,setStep]=useState(0),[confirmed,setConfirmed]=useState(false);const key=useRef<string|null>(null);const submitted=useRef<string|null>(null);
 const critical=['assign_plan','suspend','cancel','automation','reactivate','adjustment','confirm_payment','reject_payment','generate_all'].includes(action);
 function change(k:string,v:unknown){setConfirmed(false);setValues(old=>{const next={...old,[k]:v};if(k==='plan_id'){const p=plans.find(p=>p.id===v);if(p){if(action==='assign_plan')for(const f of terms)next[f.key]=p[f.key]??'';else if(action==='create_business')next.trial_days=p.trial_days;}}if(k==='kind'&&v==='transferencia')next.requires_verification=true;return next;});}
 async function submit(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();if(busy)return;if(action==='create_business'&&step<6){setStep(step+1);return;}setBusy(true);setError('');try{
  const input:PlatformRow={...values,...(academyId?{academy_id:academyId}:{})};
  for(const f of fields){if(f.type==='checkbox')input[f.key]=Boolean(values[f.key]);if(f.key==='max_students')input[f.key]=values[f.key]===''?null:values[f.key];else if(!f.required&&values[f.key]==='')delete input[f.key];}
  if(action==='automation')input.preview_token=preview?.token;
  const valid=platformValues(action,input);const signature=JSON.stringify(valid);if(submitted.current!==signature){key.current=crypto.randomUUID();submitted.current=signature;}
  const response=await fetch(`/api/platform/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:key.current,data:valid})});const result=await response.json();if(!response.ok||result.error)throw Error(result.error??'No se pudo guardar.');
  onSaved(result);
 }catch(e){setError(safeError(e));}finally{setBusy(false);}}
 function input(f:Field){const v=values[f.key];
  if(f.type==='modules')return <fieldset className="platform-checks"><legend>{f.label}</legend>{optionalModules.map(m=><label key={m}><input type="checkbox" checked={(v as string[]).includes(m)} onChange={e=>change(f.key,e.target.checked?[...(v as string[]),m]:(v as string[]).filter(x=>x!==m))}/>{moduleNames[m]}</label>)}<small>Punto de venta requiere inventario. Caja, cobros y gastos permanecen disponibles.</small></fieldset>;
  if(f.type==='applications'){const lines=v as PlatformRow[];return <fieldset className="platform-applications"><legend>{f.label}</legend>{lines.map((line,i)=><div key={i}><label>Cargo<select aria-label="Cargo" required value={String(line.charge_id)} onChange={e=>change(f.key,lines.map((x,j)=>j===i?{...x,charge_id:e.target.value}:x))}><option value="">Selecciona un cargo</option>{charges.filter(c=>Number(c.balance)>0).map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.due_on)} · {formatMoney(c.balance,String(c.currency))}</option>)}</select></label><label>Importe aplicado<input aria-label="Importe aplicado" type="number" required min="0.01" step="0.01" value={String(line.amount)} onChange={e=>change(f.key,lines.map((x,j)=>j===i?{...x,amount:e.target.value}:x))}/></label>{lines.length>1&&<button type="button" className="btn small" onClick={()=>change(f.key,lines.filter((_,j)=>j!==i))}>Quitar</button>}</div>)}<button type="button" className="btn small" onClick={()=>change(f.key,[...lines,{charge_id:'',amount:''}])}>Agregar aplicación</button><p>Distribuye el importe completo. Una transferencia pendiente reserva el saldo hasta su confirmación o rechazo.</p></fieldset>;}
  if(f.type==='checkbox')return <label className="platform-checkbox"><input type="checkbox" checked={Boolean(v)} onChange={e=>change(f.key,e.target.checked)}/>{f.label}</label>;
  return <label>{f.label}{f.type==='select'?<select aria-label={f.label} required={f.required} value={String(v)} onChange={e=>change(f.key,e.target.value)}><option value="">Selecciona…</option>{f.options?.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:f.type==='textarea'?<textarea aria-label={f.label} required={f.required} maxLength={4000} value={String(v)} onChange={e=>change(f.key,e.target.value)}/>:<input aria-label={f.label} required={f.required} type={f.type} step={f.type==='number'?'0.01':undefined} value={String(v)} maxLength={300} onChange={e=>change(f.key,e.target.value)}/>}</label>;
 }
 const selectedPlan=plans.find(p=>p.id===values.plan_id);
 return <div className="dialog-backdrop"><section className="form-dialog platform-dialog" role="dialog" aria-modal="true" aria-labelledby="platform-form-title"><div className="dialog-top"><div><span className="eyebrow">ADMINISTRACIÓN COMERCIAL</span><h2 id="platform-form-title">{actionNames[action]}</h2></div><button className="icon-btn" aria-label="Cerrar formulario" disabled={busy} onClick={onClose}>×</button></div><form onSubmit={submit}>
 {action==='create_business'&&<div className="platform-steps"><span>Paso {step+1} de 7</span><strong>{['Datos del negocio','Propietario','Moneda y zona horaria','Sucursal inicial','Plan y ciclo de cobro','Inicio y prueba','Revisión y confirmación'][step]}</strong></div>}
 <div className="form-grid">{(action==='create_business'?businessSteps[step]:fields).map(f=><div key={f.key} className={['modules','applications'].includes(f.type??'')?'platform-field-wide':''}>{input(f)}</div>)}
 {action==='create_business'&&step===4&&selectedPlan&&<p>{selectedPlan.description as string} · {formatMoney(selectedPlan.price,String(selectedPlan.currency))} / {String(selectedPlan.cycle)}</p>}
 {action==='create_business'&&step===6&&<div className="platform-field-wide"><dl className="platform-review">{businessSteps.slice(0,6).flat().map(f=><div key={f.key}><dt>{f.label}</dt><dd>{f.key==='plan_id'?`${selectedPlan?.name} · ${formatMoney(selectedPlan?.price,String(selectedPlan?.currency??'NIO'))} / ${selectedPlan?.cycle}`:String(values[f.key]||'—')}</dd></div>)}</dl><p>Se creará el negocio, sus roles, sucursal y suscripción. La invitación se enviará después del alta y puede reintentarse desde la ficha.</p><label className="platform-checkbox"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Revisé los datos y autorizo el alta.</label></div>}
 {action==='automation'&&<div className="platform-field-wide"><h3>Negocios que quedarían suspendidos</h3>{((preview?.businesses??[]) as PlatformRow[]).length?((preview?.businesses??[]) as PlatformRow[]).map(b=><p key={String(b.academy_id)}>{String(b.commercial_name)}</p>):<p>Ningún negocio afectado en esta vista previa.</p>}<small>El servidor comprobará que la vista previa siga vigente al confirmar.</small></div>}
 {critical&&<div className="platform-field-wide notice"><label className="platform-checkbox"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirmo esta operación y sus condiciones.</label></div>}
 </div>{error&&<div className="error" role="alert">{error}</div>}<div className="dialog-footer">{action==='create_business'&&step>0&&<button type="button" className="btn" disabled={busy} onClick={()=>setStep(step-1)}>Anterior</button>}<button type="button" className="btn" disabled={busy} onClick={onClose}>Cancelar</button><button className="btn primary" disabled={busy||(critical&&!confirmed)}>{busy?'Guardando…':action==='create_business'&&step<6?'Continuar':'Confirmar y guardar'}</button></div></form></section></div>;
}
