'use client';
import { useState } from 'react';
import type { AppContext } from '@/lib/context';
import { safeError } from '@/lib/validation';
export function ServiceRecovery({context}:{context:AppContext}){
 const [data,setData]=useState<Record<string,unknown>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState(''),[reviewed,setReviewed]=useState(false),[done,setDone]=useState(false),[key]=useState(()=>crypto.randomUUID());
 if(!context.service.recovery_required||!context.service.owner||done)return null;
 async function review(){setBusy(true);try{const r=await fetch(`/api/academy/recovery?academy=${context.academy.id}`);const d=await r.json();if(!r.ok||d.error)throw Error(d.error);setData(d);}catch(e){setError(safeError(e));}finally{setBusy(false);}}
 async function resume(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const r=await fetch('/api/academy/recovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({academy:context.academy.id,reason,reviewed,key})});const d=await r.json();if(!r.ok||d.error)throw Error(d.error);setDone(true);}catch(e){setError(safeError(e));}finally{setBusy(false);}}
 return <section className="card platform-conditions"><h2>Revisar automatizaciones pendientes</h2><p>El servicio está activo. Las automatizaciones operativas siguen pausadas hasta revisar los períodos pendientes.</p>{!data?<button className="btn" disabled={busy} onClick={review}>Revisar períodos pendientes</button>:<><p>{String(data.warning)}</p>{['memberships','expenses'].map(k=><div key={k}><h3>{k==='memberships'?'Membresías pendientes':'Gastos recurrentes pendientes'}</h3>{(data[k] as Record<string,unknown>[]).length?(data[k] as Record<string,unknown>[]).map(r=><p key={String(r.id)}>{String(r.name??r.description)} · {String(r.next_charge_on??r.next_due_on)} · {String(r.amount)} {String(r.currency??context.academy.currency)}</p>):<p>No hay registros pendientes en esta categoría.</p>}</div>)}<form onSubmit={resume} className="auth-form"><label>Motivo de reanudación<input required minLength={5} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="platform-checkbox"><input type="checkbox" required checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Revisé los pendientes y autorizo su recuperación en el próximo proceso configurado.</label><button className="btn" disabled={busy||!reviewed}>Reanudar automatizaciones operativas</button></form></>}{error&&<div className="error" role="alert">{error}</div>}</section>;
}
