'use client';
import { useEffect,useRef,useState } from 'react';
import { Download,Upload,X } from 'lucide-react';
import type { AppContext } from '@/lib/context';
import type { ImportLine } from '@/domains/students/import';
import { csv } from '@/lib/csv';
export function ImportStudents({context,onClose,onSaved}:{context:AppContext;onClose:()=>void;onSaved:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),retry=useRef(crypto.randomUUID());const [text,setText]=useState(''),[lines,setLines]=useState<ImportLine[]>([]),[pending,setPending]=useState(false),[error,setError]=useState(''),[include,setInclude]=useState(false);
 useEffect(()=>{dialog.current?.showModal();},[]);
 async function run(mode:string){setPending(true);setError('');try{const response=await fetch('/api/students/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({academy:context.academy.id,branch:context.branch,csv:text,mode,duplicates:include?'include':'skip',key:retry.current})});const data=await response.json();if(data.error)throw Error(data.error);if(mode==='preview')setLines(data.lines);else{onSaved();onClose();}}catch(error){setError(error instanceof Error?error.message:String(error));}finally{setPending(false);}}
 const errors=lines.filter(line=>line.errors.length>0);const duplicates=lines.filter(line=>line.duplicate);
 function downloadErrors(){const url=URL.createObjectURL(new Blob([csv(['line','name','errors'],errors.map(row=>({line:row.line,name:row.data.name,errors:row.errors})))],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='errores-estudiantes.csv';anchor.click();URL.revokeObjectURL(url);}
 return <dialog ref={dialog} className="form-dialog" onCancel={onClose}><div className="dialog-top"><div><span className="eyebrow">ESTUDIANTES</span><h2>Importar CSV</h2></div><button className="icon-btn" aria-label="Cerrar importación" onClick={onClose}><X/></button></div><div className="import-content"><p>Hasta 500 estudiantes por lote. Revisa los errores y los posibles duplicados antes de guardar.</p><a className="btn small" href={'data:text/csv;charset=utf-8,'+encodeURIComponent('\uFEFFname,email,phone,birth_date,joined_on,status\r\n')} download="plantilla-estudiantes.csv"><Download size={16}/>Descargar plantilla</a><label>Archivo CSV<input type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(file){if(file.size>1000000){setError('El archivo supera 1 MB.');return;}setText(await file.text());setLines([]);retry.current=crypto.randomUUID();}}}/></label><button className="btn" disabled={!text||pending} onClick={()=>run('preview')}><Upload size={16}/>Validar archivo</button>{lines.length>0&&<><div className="notice">{lines.length} filas · {errors.length} con errores · {duplicates.length} posibles duplicados</div><div className="table-scroll"><table><thead><tr><th>Fila</th><th>Nombre</th><th>Revisión</th></tr></thead><tbody>{lines.map(row=><tr key={row.line}><td>{row.line}</td><td>{row.data.name}</td><td>{row.errors.join(' · ')||(row.duplicate?'Posible duplicado':'Válido')}</td></tr>)}</tbody></table></div><label className="checkbox-field"><input type="checkbox" checked={include} onChange={e=>{setInclude(e.target.checked);retry.current=crypto.randomUUID();}}/>Incluir los posibles duplicados; de lo contrario se omitirán</label>{errors.length>0&&<button className="btn small" onClick={downloadErrors}>Descargar errores</button>}<button className="btn primary" disabled={pending||errors.length>0} onClick={()=>run('commit')}>Importar {include?lines.length:lines.length-duplicates.length} estudiantes</button></>}{error&&<div className="error" role="alert">{error}</div>}</div></dialog>;
}
