'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import type { AppContext } from '@/lib/context';
import { allowed } from '@/lib/money';
export function StudentProfile({context,id,revision}:{context:AppContext;id:string;revision:number}){
 const [student,setStudent]=useState<Record<string,unknown>|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch(`/api/data/students?academy=${context.academy.id}&student=${id}${context.branch?`&branch=${context.branch}`:''}`,{signal:controller.signal}).then(r=>r.json()).then(data=>setStudent(data.rows?.[0]??null)).catch(()=>{});return()=>controller.abort();},[context.academy.id,context.branch,id,revision]);
 async function collection(){const response=await fetch(`/api/collection?academy=${context.academy.id}&student=${id}`);const data=await response.json();setMessage(data.error??data.message);}
 return <section className="card student-profile">{student&&<><div className="profile-heading">{student.photo_path&&allowed(context.permissions,'documents.read')?<Image unoptimized width={64} height={64} src={`/api/students/${id}/photo?academy=${context.academy.id}`} alt={`Fotografía de ${student.name}`}/>:<span className="profile-initial">{String(student.name)[0]}</span>}<div><span className="eyebrow">EXPEDIENTE</span><h2>{String(student.name)}</h2><p>{String(student.status)} · Ingreso {String(student.joined_on).slice(0,10)}</p></div></div><div className="student-facts"><div><small>Contacto</small><strong>{String(student.phone??'Sin teléfono')}</strong><span>{String(student.email??'Sin correo')}</span></div><div><small>Emergencia</small><strong>{String(student.emergency_name??'Por configurar')}</strong><span>{String(student.emergency_phone??'Sin teléfono')}</span></div><div><small>Disciplina y grupo</small><strong>{String((student._labels as Record<string,string>)?.discipline_id??'Por configurar')}</strong><span>{String((student._labels as Record<string,string>)?.group_id??'Sin grupo')}</span></div></div>{allowed(context.permissions,'billing.read')&&<div className="profile-actions"><Link target="_blank" className="btn small" href={`/estado-cuenta/${id}?academy=${context.academy.id}`}>Imprimir estado de cuenta</Link><button className="btn small" onClick={collection}>Generar mensaje de cobranza</button></div>}{message&&<label className="collection-message">Mensaje para uso manual<textarea readOnly value={message}/><small>Selecciona y copia el texto. El sistema no envía mensajes.</small></label>}</>}</section>;
}
