import { notFound,redirect } from 'next/navigation';
import { getContext,requirePermission } from '@/lib/context';
import { uuid } from '@/lib/validation';
import { formatMoney } from '@/lib/money';
import { PrintButton } from '@/components/print-button';
import Decimal from 'decimal.js';
export const dynamic='force-dynamic';
export default async function Receipt({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{academy?:string}>}){
 let ctx;try{ctx=await getContext((await searchParams).academy);requirePermission(ctx.context,'billing.read');}catch{redirect('/login');}
 const {client,context}=ctx;const {id}=await params;const payment=await client.from('payments').select('*').eq('id',uuid.parse(id)).eq('academy_id',context.academy.id).single();if(payment.error||!payment.data)notFound();
 const p=payment.data;const [applications,student,method,branch]=await Promise.all([client.from('payment_applications').select('amount,charge_id').eq('payment_id',p.id),p.student_id?client.from('students').select('name').eq('id',p.student_id).single():Promise.resolve({data:null}),client.from('payment_methods').select('name').eq('id',p.method_id).single(),client.from('branches').select('name').eq('id',p.branch_id).single()]);
 if(applications.error||method.error||branch.error)throw Error('No se pudo cargar el recibo.');
 const chargeIds=(applications.data??[]).map(line=>line.charge_id);const charges=chargeIds.length?await client.from('charges').select('id,description,student_id').in('id',chargeIds):{data:[],error:null};if(charges.error)throw Error('No se pudieron cargar los conceptos.');
 const studentIds=[...new Set((charges.data??[]).map(c=>c.student_id).filter(Boolean))];const students=studentIds.length?await client.from('students').select('id,name').in('id',studentIds):{data:[],error:null};
 const lines=(applications.data??[]).map(line=>{const c=charges.data?.find(c=>c.id===line.charge_id);return {amount:line.amount,description:c?.description??'Concepto fuera del acceso actual',name:students.data?.find(s=>s.id===c?.student_id)?.name??'Cliente externo'};});
 const unallocated=new Decimal(p.amount).minus(lines.reduce((s,line)=>s.plus(line.amount),new Decimal(0))).toFixed(2);
 return <main className="receipt-page"><header className="receipt-header"><div><span className="eyebrow">COMPROBANTE DE PAGO</span><h1 className="receipt-title">{context.academy.name}</h1><p>{context.academy.contact}<br/>{branch.data?.name}</p></div><div><strong>Recibo #{p.receipt_prefix}{p.receipt_number}</strong><p>{new Intl.DateTimeFormat(context.academy.locale,{dateStyle:'long',timeStyle:'short',timeZone:context.academy.timezone}).format(new Date(p.created_at))}</p></div></header><div className="receipt-meta"><p>Recibido de: <strong>{student.data?.name??'Responsable o cliente externo'}</strong></p><p>Medio: {method.data?.name} · Estado: <strong>{p.status==='confirmado'?'Confirmado':'Pendiente de verificación'}</strong></p>{p.reference&&<p>Referencia: {p.reference}</p>}{p.status==='pendiente'&&<div className="notice">Este pago aún no salda la deuda.</div>}</div><table><thead><tr><th>Concepto</th><th>Estudiante</th><th>Aplicado</th></tr></thead><tbody>{lines.map((line,index)=><tr key={index}><td>{line.description}</td><td>{line.name}</td><td>{formatMoney(line.amount,context.academy.currency,context.academy.locale)}</td></tr>)}</tbody></table><div className="receipt-total">Total: {formatMoney(p.amount,context.academy.currency,context.academy.locale)}</div>{Number(p.tendered)>Number(p.amount)&&<p>Entregado: {formatMoney(p.tendered,context.academy.currency,context.academy.locale)} · Cambio: {formatMoney(new Decimal(p.tendered).minus(p.amount).toFixed(2),context.academy.currency,context.academy.locale)}</p>}<p>Importe sin aplicar a cargos: {formatMoney(unallocated,context.academy.currency,context.academy.locale)}</p><footer className="receipt-footer"><p>{context.academy.receipt_footer??'Conserva este comprobante para tu control.'}</p><small>Comprobante administrativo de pago. Los reembolsos y aplicaciones posteriores se consultan en el historial.</small><br/><PrintButton/></footer></main>;
}
