-- No demo data or accounts. Every operation uses an authenticated actor.
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;
create table public.academies (
 id uuid primary key default gen_random_uuid(), name text not null check(length(name) between 2 and 120),
 country text not null, currency text not null check(currency ~ '^[A-Z]{3}$'), timezone text not null,
 primary_color text not null default '#215c50' check(primary_color ~ '^#[0-9a-fA-F]{6}$'),
 logo_path text, contact text, receipt_footer text, grace_days int not null default 5 check(grace_days between 0 and 90),
 billing_day int check(billing_day between 1 and 31), allow_negative_stock boolean not null default false,
 expense_approval_limit numeric(14,2) not null default 0 check(expense_approval_limit>=0),
 collection_template text not null default 'Hola {nombre}, tu saldo pendiente es {saldo}. Comunícate con recepción para acordar tu pago.',
 receipt_prefix text not null default 'REC', created_at timestamptz not null default now()
);
create table public.branches (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), name text not null, address text, phone text, active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.roles (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), name text not null, permissions text[] not null, active boolean not null default true, unique(academy_id,name), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.internal_members (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), user_id uuid not null references auth.users(id), name text not null, active boolean not null default true, all_branches boolean not null default false, branch_ids uuid[] not null default '{}', unique(academy_id,user_id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.member_roles (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), member_id uuid not null, foreign key(academy_id,member_id) references public.internal_members(academy_id,id), role_id uuid not null, foreign key(academy_id,role_id) references public.roles(academy_id,id), unique(member_id,role_id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.rooms (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), name text not null, capacity int not null check(capacity>0), active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.disciplines (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), name text not null, active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.belts (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), discipline_id uuid not null, foreign key(academy_id,discipline_id) references public.disciplines(academy_id,id), name text not null, rank int not null default 0, active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.student_groups (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), name text not null, min_age int, max_age int, active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.contacts (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), name text not null, email text, phone text, address text, linked_user_id uuid references auth.users(id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.students (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), name text not null check(length(name)>1), email text, phone text, birth_date date, joined_on date not null default current_date, status text not null default 'activo' check(status in ('activo','pausado','retirado')), status_reason text, emergency_name text, emergency_phone text, photo_path text, payer_id uuid , foreign key(academy_id,payer_id) references public.contacts(academy_id,id), group_id uuid , foreign key(academy_id,group_id) references public.student_groups(academy_id,id), discipline_id uuid , foreign key(academy_id,discipline_id) references public.disciplines(academy_id,id), linked_user_id uuid references auth.users(id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.student_guardians (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), student_id uuid not null, foreign key(academy_id,student_id) references public.students(academy_id,id), contact_id uuid not null, foreign key(academy_id,contact_id) references public.contacts(academy_id,id), relationship text not null, is_payer boolean not null default false, unique(student_id,contact_id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.student_progress (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), student_id uuid not null, foreign key(academy_id,student_id) references public.students(academy_id,id), belt_id uuid not null, foreign key(academy_id,belt_id) references public.belts(academy_id,id), degree int not null default 0 check(degree>=0), promoted_on date not null, notes text, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.student_notes (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), student_id uuid not null, foreign key(academy_id,student_id) references public.students(academy_id,id), body text not null, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.documents (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), student_id uuid , foreign key(academy_id,student_id) references public.students(academy_id,id), title text not null, path text not null unique, mime_type text not null check(mime_type in ('application/pdf','image/jpeg','image/png')), size_bytes int not null check(size_bytes between 1 and 5242880), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.prospects (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), name text not null, email text, phone text, status text not null default 'nuevo' check(status in ('nuevo','prueba','convertido','descartado')), trial_at timestamptz, notes text, student_id uuid , foreign key(academy_id,student_id) references public.students(academy_id,id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.plans (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), name text not null, kind text not null check(kind in ('ilimitado','semanal','paquete','visita','privada','familiar','servicio')), discipline_id uuid , foreign key(academy_id,discipline_id) references public.disciplines(academy_id,id), branch_id uuid , foreign key(academy_id,branch_id) references public.branches(academy_id,id), active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.plan_versions (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), plan_id uuid not null, foreign key(academy_id,plan_id) references public.plans(academy_id,id), price numeric(14,2) not null check(price>=0), months int not null default 1 check(months between 1 and 12), valid_days int not null default 30 check(valid_days>0), weekly_limit int check(weekly_limit>0), class_count int check(class_count>0), effective_on date not null, renewable boolean not null default true, unique(plan_id,effective_on), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.memberships (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), student_id uuid not null, foreign key(academy_id,student_id) references public.students(academy_id,id), plan_version_id uuid not null, foreign key(academy_id,plan_version_id) references public.plan_versions(academy_id,id), starts_on date not null, ends_on date not null, next_charge_on date not null, anchor_day int not null check(anchor_day between 1 and 31), billing_mode text not null default 'aniversario' check(billing_mode in ('aniversario','fijo')), status text not null default 'activa' check(status in ('activa','congelada','cancelada')), remaining_classes int check(remaining_classes>=0), discount numeric(14,2) not null default 0 check(discount>=0), frozen_until date, unique(student_id,plan_version_id,starts_on), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.membership_events (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), membership_id uuid not null, foreign key(academy_id,membership_id) references public.memberships(academy_id,id), action text not null, reason text not null, actor uuid not null, effective_on date not null, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.charges (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), student_id uuid , foreign key(academy_id,student_id) references public.students(academy_id,id), membership_id uuid , foreign key(academy_id,membership_id) references public.memberships(academy_id,id), description text not null, amount numeric(14,2) not null check(amount>=0), due_on date not null, period_on date, source text not null default 'manual', status text not null default 'emitido' check(status in ('emitido','anulado')), unique(membership_id,period_on), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.charge_adjustments (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), charge_id uuid not null, foreign key(academy_id,charge_id) references public.charges(academy_id,id), amount numeric(14,2) not null check(amount<>0), reason text not null, actor uuid not null, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.payment_methods (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), name text not null, kind text not null check(kind in ('efectivo','transferencia','tarjeta','otro')), requires_verification boolean not null default false, fee_percent numeric(7,4) not null default 0 check(fee_percent between 0 and 100), fee_fixed numeric(14,2) not null default 0 check(fee_fixed>=0), active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.accounts (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), name text not null, kind text not null check(kind in ('recepcion','chica','banco')), active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.cash_sessions (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), account_id uuid not null, foreign key(academy_id,account_id) references public.accounts(academy_id,id), cashier uuid not null, opened_at timestamptz not null default now(), closed_at timestamptz, opening_amount numeric(14,2) not null check(opening_amount>=0), expected numeric(14,2), counted numeric(14,2), difference numeric(14,2), reason text, approved_by uuid, created_at timestamptz not null default now(), unique(academy_id,id));
create unique index one_open_cash_session on public.cash_sessions(account_id) where closed_at is null;
create table public.payments (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), student_id uuid , foreign key(academy_id,student_id) references public.students(academy_id,id), payer_id uuid , foreign key(academy_id,payer_id) references public.contacts(academy_id,id), account_id uuid not null, foreign key(academy_id,account_id) references public.accounts(academy_id,id), method_id uuid not null, foreign key(academy_id,method_id) references public.payment_methods(academy_id,id), session_id uuid , foreign key(academy_id,session_id) references public.cash_sessions(academy_id,id), amount numeric(14,2) not null check(amount>0), tendered numeric(14,2) not null check(tendered>=amount), fee numeric(14,2) not null default 0 check(fee>=0), status text not null check(status in ('pendiente','confirmado')), reference text, receipt_number bigint not null, actor uuid not null, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.payment_applications (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), payment_id uuid not null, foreign key(academy_id,payment_id) references public.payments(academy_id,id), charge_id uuid not null, foreign key(academy_id,charge_id) references public.charges(academy_id,id), amount numeric(14,2) not null check(amount>0), confirmed boolean not null default false, unique(payment_id,charge_id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.account_movements (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), account_id uuid not null, foreign key(academy_id,account_id) references public.accounts(academy_id,id), session_id uuid , foreign key(academy_id,session_id) references public.cash_sessions(academy_id,id), amount numeric(14,2) not null check(amount<>0), kind text not null check(kind in ('cobro','egreso','transferencia','aporte','retiro','apertura','ajuste','reembolso','comision')), source_id uuid not null, description text not null, actor uuid not null, reconciled_on date, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.refunds (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), payment_id uuid not null, foreign key(academy_id,payment_id) references public.payments(academy_id,id), amount numeric(14,2) not null check(amount>0), reason text not null, actor uuid not null, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.refund_applications (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), refund_id uuid not null, foreign key(academy_id,refund_id) references public.refunds(academy_id,id), application_id uuid not null, foreign key(academy_id,application_id) references public.payment_applications(academy_id,id), amount numeric(14,2) not null check(amount>0), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.transfers (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), from_account_id uuid not null, foreign key(academy_id,from_account_id) references public.accounts(academy_id,id), to_account_id uuid not null, foreign key(academy_id,to_account_id) references public.accounts(academy_id,id), amount numeric(14,2) not null check(amount>0), reason text not null, check(from_account_id<>to_account_id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.commitments (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), student_id uuid not null, foreign key(academy_id,student_id) references public.students(academy_id,id), due_on date not null, amount numeric(14,2) not null check(amount>0), notes text not null, status text not null default 'pendiente' check(status in ('pendiente','cumplido','incumplido')), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.product_categories (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), name text not null, active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.products (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), category_id uuid , foreign key(academy_id,category_id) references public.product_categories(academy_id,id), name text not null, kind text not null default 'venta' check(kind in ('venta','consumible','equipo','servicio')), active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.product_variants (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), product_id uuid not null, foreign key(academy_id,product_id) references public.products(academy_id,id), name text not null, code text not null, size text, color text, unit text not null default 'unidad', price numeric(14,2) not null check(price>=0), min_stock numeric(14,3) not null default 0 check(min_stock>=0), active boolean not null default true, unique(academy_id,code), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.stock (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), variant_id uuid not null, foreign key(academy_id,variant_id) references public.product_variants(academy_id,id), quantity numeric(14,3) not null default 0 check(quantity>=0), average_cost numeric(14,4) not null default 0 check(average_cost>=0), unique(branch_id,variant_id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.inventory_movements (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), variant_id uuid not null, foreign key(academy_id,variant_id) references public.product_variants(academy_id,id), quantity numeric(14,3) not null check(quantity<>0), unit_cost numeric(14,4) not null check(unit_cost>=0), kind text not null, source_id uuid not null, reason text not null, actor uuid not null, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.suppliers (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), name text not null, email text, phone text, tax_id text, active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.expenses (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), supplier_id uuid , foreign key(academy_id,supplier_id) references public.suppliers(academy_id,id), description text not null, category text not null, amount numeric(14,2) not null check(amount>0), due_on date not null, incurred_on date not null, status text not null default 'pendiente' check(status in ('pendiente','aprobado','anulado')), approved_by uuid, source text not null default 'operativo', source_id uuid, document_path text, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.expense_payments (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), expense_id uuid not null, foreign key(academy_id,expense_id) references public.expenses(academy_id,id), account_id uuid not null, foreign key(academy_id,account_id) references public.accounts(academy_id,id), session_id uuid , foreign key(academy_id,session_id) references public.cash_sessions(academy_id,id), amount numeric(14,2) not null check(amount>0), actor uuid not null, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.expense_templates (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), description text not null, category text not null, amount numeric(14,2) not null check(amount>0), next_due_on date not null, months int not null default 1 check(months between 1 and 12), active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.purchases (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), supplier_id uuid not null, foreign key(academy_id,supplier_id) references public.suppliers(academy_id,id), expense_id uuid not null, foreign key(academy_id,expense_id) references public.expenses(academy_id,id), ordered_on date not null, status text not null default 'pedido' check(status in ('pedido','parcial','recibido','anulado')), reference text, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.purchase_lines (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), purchase_id uuid not null, foreign key(academy_id,purchase_id) references public.purchases(academy_id,id), variant_id uuid not null, foreign key(academy_id,variant_id) references public.product_variants(academy_id,id), quantity numeric(14,3) not null check(quantity>0), unit_cost numeric(14,4) not null check(unit_cost>=0), received numeric(14,3) not null default 0 check(received between 0 and quantity), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.stock_transfers (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), to_branch_id uuid not null, foreign key(academy_id,to_branch_id) references public.branches(academy_id,id), variant_id uuid not null, foreign key(academy_id,variant_id) references public.product_variants(academy_id,id), quantity numeric(14,3) not null check(quantity>0), unit_cost numeric(14,4) not null, status text not null default 'enviado' check(status in ('enviado','recibido')), reason text not null, check(branch_id<>to_branch_id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.equipment (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), variant_id uuid , foreign key(academy_id,variant_id) references public.product_variants(academy_id,id), name text not null, location text not null, status text not null default 'operativo' check(status in ('operativo','mantenimiento','baja')), maintenance_on date, notes text, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.sales (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), student_id uuid , foreign key(academy_id,student_id) references public.students(academy_id,id), customer_name text, charge_id uuid not null, foreign key(academy_id,charge_id) references public.charges(academy_id,id), total numeric(14,2) not null check(total>=0), discount numeric(14,2) not null default 0, seller uuid not null, status text not null default 'confirmada' check(status in ('confirmada','devuelta')), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.sale_lines (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), sale_id uuid not null, foreign key(academy_id,sale_id) references public.sales(academy_id,id), variant_id uuid not null, foreign key(academy_id,variant_id) references public.product_variants(academy_id,id), quantity numeric(14,3) not null check(quantity>0), unit_price numeric(14,2) not null check(unit_price>=0), unit_cost numeric(14,4) not null check(unit_cost>=0), discount numeric(14,2) not null default 0, returned numeric(14,3) not null default 0 check(returned between 0 and quantity), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.employees (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), name text not null, email text, phone text, position text not null, status text not null default 'activo' check(status in ('activo','inactivo')), linked_user_id uuid references auth.users(id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.compensation_versions (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), employee_id uuid not null, foreign key(academy_id,employee_id) references public.employees(academy_id,id), effective_on date not null, fixed_amount numeric(14,2) not null default 0 check(fixed_amount>=0), hourly_rate numeric(14,2) not null default 0 check(hourly_rate>=0), class_rate numeric(14,2) not null default 0 check(class_rate>=0), sale_percent numeric(7,4) not null default 0 check(sale_percent between 0 and 100), private_percent numeric(7,4) not null default 0 check(private_percent between 0 and 100), accrual text not null default 'cobro' check(accrual in ('cobro','venta')), unique(employee_id,effective_on), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.staff_activities (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), employee_id uuid not null, foreign key(academy_id,employee_id) references public.employees(academy_id,id), compensation_version_id uuid not null, foreign key(academy_id,compensation_version_id) references public.compensation_versions(academy_id,id), kind text not null check(kind in ('hora','clase','venta','privada','ajuste','anticipo')), units numeric(14,3) not null default 1, base_amount numeric(14,2) not null default 0, earned numeric(14,2) not null, activity_on date not null, source_id uuid, approved boolean not null default false, unique(employee_id,kind,source_id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.settlements (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), employee_id uuid not null, foreign key(academy_id,employee_id) references public.employees(academy_id,id), expense_id uuid not null, foreign key(academy_id,expense_id) references public.expenses(academy_id,id), from_on date not null, to_on date not null, total numeric(14,2) not null check(total>=0), status text not null default 'revision' check(status in ('revision','aprobada','pagada')), unique(employee_id,from_on,to_on), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.settlement_lines (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), settlement_id uuid not null, foreign key(academy_id,settlement_id) references public.settlements(academy_id,id), activity_id uuid not null, foreign key(academy_id,activity_id) references public.staff_activities(academy_id,id), amount numeric(14,2) not null, unique(activity_id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.class_templates (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), name text not null, discipline_id uuid not null, foreign key(academy_id,discipline_id) references public.disciplines(academy_id,id), room_id uuid not null, foreign key(academy_id,room_id) references public.rooms(academy_id,id), instructor_id uuid not null, foreign key(academy_id,instructor_id) references public.employees(academy_id,id), weekday int not null check(weekday between 0 and 6), starts_time time not null, duration_minutes int not null check(duration_minutes>0), capacity int not null check(capacity>0), level text, age_group text, active boolean not null default true, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.classes (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), name text not null, discipline_id uuid not null, foreign key(academy_id,discipline_id) references public.disciplines(academy_id,id), room_id uuid not null, foreign key(academy_id,room_id) references public.rooms(academy_id,id), instructor_id uuid not null, foreign key(academy_id,instructor_id) references public.employees(academy_id,id), substitute_id uuid , foreign key(academy_id,substitute_id) references public.employees(academy_id,id), template_id uuid , foreign key(academy_id,template_id) references public.class_templates(academy_id,id), starts_at timestamptz not null, ends_at timestamptz not null, capacity int not null check(capacity>0), kind text not null default 'regular' check(kind in ('regular','privada','prueba','evento','seminario')), status text not null default 'programada' check(status in ('programada','cancelada','impartida')), reason text, check(ends_at>starts_at), unique(template_id,starts_at), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.reservations (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), class_id uuid not null, foreign key(academy_id,class_id) references public.classes(academy_id,id), student_id uuid not null, foreign key(academy_id,student_id) references public.students(academy_id,id), status text not null check(status in ('reservada','espera','cancelada','ausente')), unique(class_id,student_id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.attendance (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), class_id uuid not null, foreign key(academy_id,class_id) references public.classes(academy_id,id), student_id uuid not null, foreign key(academy_id,student_id) references public.students(academy_id,id), membership_id uuid , foreign key(academy_id,membership_id) references public.memberships(academy_id,id), exception_reason text, actor uuid not null, unique(class_id,student_id), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.holidays (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid not null, foreign key(academy_id,branch_id) references public.branches(academy_id,id), day date not null, reason text not null, unique(branch_id,day), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.notifications (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid , foreign key(academy_id,branch_id) references public.branches(academy_id,id), kind text not null, title text not null, entity_id uuid, read_at timestamptz, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.audit_log (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), branch_id uuid , foreign key(academy_id,branch_id) references public.branches(academy_id,id), actor uuid, entity text not null, entity_id uuid, action text not null, reason text, details jsonb not null default '{}', created_at timestamptz not null default now(), unique(academy_id,id));
create table public.operation_keys (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), key uuid not null, action text not null, payload jsonb not null, result jsonb, unique(academy_id,key), created_at timestamptz not null default now(), unique(academy_id,id));
create table public.job_runs (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), started_at timestamptz not null default now(), finished_at timestamptz, generated int not null default 0, remaining boolean not null default false, error text, created_at timestamptz not null default now(), unique(academy_id,id));
create table public.document_counters (id uuid primary key default gen_random_uuid(), academy_id uuid not null references public.academies(id), kind text not null, next_number bigint not null default 1, unique(academy_id,kind), created_at timestamptz not null default now(), unique(academy_id,id));

create function private.has_permission(a uuid, b uuid, p text) returns boolean
language sql stable security definer set search_path = '' as $$
 select auth.uid() is not null and exists (
 select 1 from public.internal_members m join public.member_roles mr on mr.member_id=m.id and mr.academy_id=m.academy_id
 join public.roles r on r.id=mr.role_id and r.academy_id=m.academy_id
 where m.user_id=auth.uid() and m.academy_id=a and m.active and r.active
 and (b is null or m.all_branches or b=any(m.branch_ids))
 and (p=any(r.permissions) or '*'=any(r.permissions)))
$$;
revoke all on function private.has_permission(uuid,uuid,text) from public;
grant execute on function private.has_permission(uuid,uuid,text) to authenticated;
create function private.immutable_academy() returns trigger language plpgsql set search_path='' as $$
begin if new.academy_id <> old.academy_id then raise exception 'No se puede cambiar la academia'; end if; return new; end $$;
create function private.audit_master() returns trigger language plpgsql security definer set search_path='' as $$
begin
 insert into public.audit_log(academy_id,actor,entity,entity_id,action) values(new.academy_id,auth.uid(),tg_table_name,new.id,tg_op);
 return new;
end $$;
alter table public.academies enable row level security;
grant select on public.academies to authenticated;
create policy academy_read on public.academies for select to authenticated using(private.has_permission(id,null,'dashboard.read'));
alter table public.branches enable row level security;
grant select on public.branches to authenticated;
create policy branches_read on public.branches for select to authenticated using (private.has_permission(academy_id,id,'settings.read'));
create trigger immutable_academy before update on public.branches for each row execute function private.immutable_academy();
create index branches_academy_idx on public.branches(academy_id);
grant insert,update on public.branches to authenticated;
create policy branches_insert on public.branches for insert to authenticated with check(private.has_permission(academy_id,id,'settings.write'));
create policy branches_update on public.branches for update to authenticated using(private.has_permission(academy_id,id,'settings.write')) with check(private.has_permission(academy_id,id,'settings.write'));
create trigger audit_master after insert or update on public.branches for each row execute function private.audit_master();
alter table public.roles enable row level security;
grant select on public.roles to authenticated;
create policy roles_read on public.roles for select to authenticated using (private.has_permission(academy_id,null,'dashboard.read'));
create trigger immutable_academy before update on public.roles for each row execute function private.immutable_academy();
create index roles_academy_idx on public.roles(academy_id);
alter table public.internal_members enable row level security;
grant select on public.internal_members to authenticated;
create policy internal_members_read on public.internal_members for select to authenticated using ((user_id=auth.uid() and active) or private.has_permission(academy_id,null,'users.manage'));
create trigger immutable_academy before update on public.internal_members for each row execute function private.immutable_academy();
create index internal_members_academy_idx on public.internal_members(academy_id);
alter table public.member_roles enable row level security;
grant select on public.member_roles to authenticated;
create policy member_roles_read on public.member_roles for select to authenticated using (private.has_permission(academy_id,null,'users.manage') or member_id in (select id from public.internal_members where user_id=auth.uid() and active));
create trigger immutable_academy before update on public.member_roles for each row execute function private.immutable_academy();
create index member_roles_academy_idx on public.member_roles(academy_id);
alter table public.rooms enable row level security;
grant select on public.rooms to authenticated;
create policy rooms_read on public.rooms for select to authenticated using (private.has_permission(academy_id,branch_id,'settings.read'));
create trigger immutable_academy before update on public.rooms for each row execute function private.immutable_academy();
create index rooms_academy_idx on public.rooms(academy_id);
grant insert,update on public.rooms to authenticated;
create policy rooms_insert on public.rooms for insert to authenticated with check(private.has_permission(academy_id,branch_id,'settings.write'));
create policy rooms_update on public.rooms for update to authenticated using(private.has_permission(academy_id,branch_id,'settings.write')) with check(private.has_permission(academy_id,branch_id,'settings.write'));
create trigger audit_master after insert or update on public.rooms for each row execute function private.audit_master();
alter table public.disciplines enable row level security;
grant select on public.disciplines to authenticated;
create policy disciplines_read on public.disciplines for select to authenticated using (private.has_permission(academy_id,null,'settings.read'));
create trigger immutable_academy before update on public.disciplines for each row execute function private.immutable_academy();
create index disciplines_academy_idx on public.disciplines(academy_id);
grant insert,update on public.disciplines to authenticated;
create policy disciplines_insert on public.disciplines for insert to authenticated with check(private.has_permission(academy_id,null,'settings.write'));
create policy disciplines_update on public.disciplines for update to authenticated using(private.has_permission(academy_id,null,'settings.write')) with check(private.has_permission(academy_id,null,'settings.write'));
create trigger audit_master after insert or update on public.disciplines for each row execute function private.audit_master();
alter table public.belts enable row level security;
grant select on public.belts to authenticated;
create policy belts_read on public.belts for select to authenticated using (private.has_permission(academy_id,null,'settings.read'));
create trigger immutable_academy before update on public.belts for each row execute function private.immutable_academy();
create index belts_academy_idx on public.belts(academy_id);
grant insert,update on public.belts to authenticated;
create policy belts_insert on public.belts for insert to authenticated with check(private.has_permission(academy_id,null,'settings.write'));
create policy belts_update on public.belts for update to authenticated using(private.has_permission(academy_id,null,'settings.write')) with check(private.has_permission(academy_id,null,'settings.write'));
create trigger audit_master after insert or update on public.belts for each row execute function private.audit_master();
alter table public.student_groups enable row level security;
grant select on public.student_groups to authenticated;
create policy student_groups_read on public.student_groups for select to authenticated using (private.has_permission(academy_id,branch_id,'settings.read'));
create trigger immutable_academy before update on public.student_groups for each row execute function private.immutable_academy();
create index student_groups_academy_idx on public.student_groups(academy_id);
grant insert,update on public.student_groups to authenticated;
create policy student_groups_insert on public.student_groups for insert to authenticated with check(private.has_permission(academy_id,branch_id,'settings.write'));
create policy student_groups_update on public.student_groups for update to authenticated using(private.has_permission(academy_id,branch_id,'settings.write')) with check(private.has_permission(academy_id,branch_id,'settings.write'));
create trigger audit_master after insert or update on public.student_groups for each row execute function private.audit_master();
alter table public.contacts enable row level security;
grant select on public.contacts to authenticated;
create policy contacts_read on public.contacts for select to authenticated using (private.has_permission(academy_id,null,'students.read'));
create trigger immutable_academy before update on public.contacts for each row execute function private.immutable_academy();
create index contacts_academy_idx on public.contacts(academy_id);
grant insert,update on public.contacts to authenticated;
create policy contacts_insert on public.contacts for insert to authenticated with check(private.has_permission(academy_id,null,'students.write'));
create policy contacts_update on public.contacts for update to authenticated using(private.has_permission(academy_id,null,'students.write')) with check(private.has_permission(academy_id,null,'students.write'));
create trigger audit_master after insert or update on public.contacts for each row execute function private.audit_master();
alter table public.students enable row level security;
grant select on public.students to authenticated;
create policy students_read on public.students for select to authenticated using (private.has_permission(academy_id,branch_id,'students.read'));
create trigger immutable_academy before update on public.students for each row execute function private.immutable_academy();
create index students_academy_idx on public.students(academy_id);
grant insert,update on public.students to authenticated;
create policy students_insert on public.students for insert to authenticated with check(private.has_permission(academy_id,branch_id,'students.write'));
create policy students_update on public.students for update to authenticated using(private.has_permission(academy_id,branch_id,'students.write')) with check(private.has_permission(academy_id,branch_id,'students.write'));
create trigger audit_master after insert or update on public.students for each row execute function private.audit_master();
alter table public.student_guardians enable row level security;
grant select on public.student_guardians to authenticated;
create policy student_guardians_read on public.student_guardians for select to authenticated using (private.has_permission(academy_id,null,'students.read') and exists(select 1 from public.students parent where parent.id=student_guardians.student_id and parent.academy_id=student_guardians.academy_id));
create trigger immutable_academy before update on public.student_guardians for each row execute function private.immutable_academy();
create index student_guardians_academy_idx on public.student_guardians(academy_id);
grant insert,update on public.student_guardians to authenticated;
create policy student_guardians_insert on public.student_guardians for insert to authenticated with check(private.has_permission(academy_id,null,'students.write') and exists(select 1 from public.students parent where parent.id=student_guardians.student_id and parent.academy_id=student_guardians.academy_id));
create policy student_guardians_update on public.student_guardians for update to authenticated using(private.has_permission(academy_id,null,'students.write') and exists(select 1 from public.students parent where parent.id=student_guardians.student_id and parent.academy_id=student_guardians.academy_id)) with check(private.has_permission(academy_id,null,'students.write') and exists(select 1 from public.students parent where parent.id=student_guardians.student_id and parent.academy_id=student_guardians.academy_id));
create trigger audit_master after insert or update on public.student_guardians for each row execute function private.audit_master();
alter table public.student_progress enable row level security;
grant select on public.student_progress to authenticated;
create policy student_progress_read on public.student_progress for select to authenticated using (private.has_permission(academy_id,null,'students.read') and exists(select 1 from public.students parent where parent.id=student_progress.student_id and parent.academy_id=student_progress.academy_id));
create trigger immutable_academy before update on public.student_progress for each row execute function private.immutable_academy();
create index student_progress_academy_idx on public.student_progress(academy_id);
grant insert,update on public.student_progress to authenticated;
create policy student_progress_insert on public.student_progress for insert to authenticated with check(private.has_permission(academy_id,null,'students.write') and exists(select 1 from public.students parent where parent.id=student_progress.student_id and parent.academy_id=student_progress.academy_id));
create policy student_progress_update on public.student_progress for update to authenticated using(private.has_permission(academy_id,null,'students.write') and exists(select 1 from public.students parent where parent.id=student_progress.student_id and parent.academy_id=student_progress.academy_id)) with check(private.has_permission(academy_id,null,'students.write') and exists(select 1 from public.students parent where parent.id=student_progress.student_id and parent.academy_id=student_progress.academy_id));
create trigger audit_master after insert or update on public.student_progress for each row execute function private.audit_master();
alter table public.student_notes enable row level security;
grant select on public.student_notes to authenticated;
create policy student_notes_read on public.student_notes for select to authenticated using (private.has_permission(academy_id,null,'notes.read') and exists(select 1 from public.students parent where parent.id=student_notes.student_id and parent.academy_id=student_notes.academy_id));
create trigger immutable_academy before update on public.student_notes for each row execute function private.immutable_academy();
create index student_notes_academy_idx on public.student_notes(academy_id);
grant insert,update on public.student_notes to authenticated;
create policy student_notes_insert on public.student_notes for insert to authenticated with check(private.has_permission(academy_id,null,'notes.write') and exists(select 1 from public.students parent where parent.id=student_notes.student_id and parent.academy_id=student_notes.academy_id));
create policy student_notes_update on public.student_notes for update to authenticated using(private.has_permission(academy_id,null,'notes.write') and exists(select 1 from public.students parent where parent.id=student_notes.student_id and parent.academy_id=student_notes.academy_id)) with check(private.has_permission(academy_id,null,'notes.write') and exists(select 1 from public.students parent where parent.id=student_notes.student_id and parent.academy_id=student_notes.academy_id));
create trigger audit_master after insert or update on public.student_notes for each row execute function private.audit_master();
alter table public.documents enable row level security;
grant select on public.documents to authenticated;
create policy documents_read on public.documents for select to authenticated using (private.has_permission(academy_id,branch_id,'documents.read'));
create trigger immutable_academy before update on public.documents for each row execute function private.immutable_academy();
create index documents_academy_idx on public.documents(academy_id);
grant insert,update on public.documents to authenticated;
create policy documents_insert on public.documents for insert to authenticated with check(private.has_permission(academy_id,branch_id,'documents.write'));
create policy documents_update on public.documents for update to authenticated using(private.has_permission(academy_id,branch_id,'documents.write')) with check(private.has_permission(academy_id,branch_id,'documents.write'));
create trigger audit_master after insert or update on public.documents for each row execute function private.audit_master();
alter table public.prospects enable row level security;
grant select on public.prospects to authenticated;
create policy prospects_read on public.prospects for select to authenticated using (private.has_permission(academy_id,branch_id,'students.read'));
create trigger immutable_academy before update on public.prospects for each row execute function private.immutable_academy();
create index prospects_academy_idx on public.prospects(academy_id);
grant insert,update on public.prospects to authenticated;
create policy prospects_insert on public.prospects for insert to authenticated with check(private.has_permission(academy_id,branch_id,'students.write'));
create policy prospects_update on public.prospects for update to authenticated using(private.has_permission(academy_id,branch_id,'students.write')) with check(private.has_permission(academy_id,branch_id,'students.write'));
create trigger audit_master after insert or update on public.prospects for each row execute function private.audit_master();
alter table public.plans enable row level security;
grant select on public.plans to authenticated;
create policy plans_read on public.plans for select to authenticated using (private.has_permission(academy_id,null,'billing.read'));
create trigger immutable_academy before update on public.plans for each row execute function private.immutable_academy();
create index plans_academy_idx on public.plans(academy_id);
grant insert,update on public.plans to authenticated;
create policy plans_insert on public.plans for insert to authenticated with check(private.has_permission(academy_id,null,'billing.write'));
create policy plans_update on public.plans for update to authenticated using(private.has_permission(academy_id,null,'billing.write')) with check(private.has_permission(academy_id,null,'billing.write'));
create trigger audit_master after insert or update on public.plans for each row execute function private.audit_master();
alter table public.plan_versions enable row level security;
grant select on public.plan_versions to authenticated;
create policy plan_versions_read on public.plan_versions for select to authenticated using (private.has_permission(academy_id,null,'billing.read'));
create trigger immutable_academy before update on public.plan_versions for each row execute function private.immutable_academy();
create index plan_versions_academy_idx on public.plan_versions(academy_id);
alter table public.memberships enable row level security;
grant select on public.memberships to authenticated;
create policy memberships_read on public.memberships for select to authenticated using (private.has_permission(academy_id,branch_id,'billing.read'));
create trigger immutable_academy before update on public.memberships for each row execute function private.immutable_academy();
create index memberships_academy_idx on public.memberships(academy_id);
alter table public.membership_events enable row level security;
grant select on public.membership_events to authenticated;
create policy membership_events_read on public.membership_events for select to authenticated using (private.has_permission(academy_id,null,'billing.read') and exists(select 1 from public.memberships parent where parent.id=membership_events.membership_id and parent.academy_id=membership_events.academy_id));
create trigger immutable_academy before update on public.membership_events for each row execute function private.immutable_academy();
create index membership_events_academy_idx on public.membership_events(academy_id);
alter table public.charges enable row level security;
grant select on public.charges to authenticated;
create policy charges_read on public.charges for select to authenticated using (private.has_permission(academy_id,branch_id,'billing.read'));
create trigger immutable_academy before update on public.charges for each row execute function private.immutable_academy();
create index charges_academy_idx on public.charges(academy_id);
alter table public.charge_adjustments enable row level security;
grant select on public.charge_adjustments to authenticated;
create policy charge_adjustments_read on public.charge_adjustments for select to authenticated using (private.has_permission(academy_id,branch_id,'billing.read'));
create trigger immutable_academy before update on public.charge_adjustments for each row execute function private.immutable_academy();
create index charge_adjustments_academy_idx on public.charge_adjustments(academy_id);
alter table public.payment_methods enable row level security;
grant select on public.payment_methods to authenticated;
create policy payment_methods_read on public.payment_methods for select to authenticated using (private.has_permission(academy_id,null,'settings.read'));
create trigger immutable_academy before update on public.payment_methods for each row execute function private.immutable_academy();
create index payment_methods_academy_idx on public.payment_methods(academy_id);
grant insert,update on public.payment_methods to authenticated;
create policy payment_methods_insert on public.payment_methods for insert to authenticated with check(private.has_permission(academy_id,null,'settings.write'));
create policy payment_methods_update on public.payment_methods for update to authenticated using(private.has_permission(academy_id,null,'settings.write')) with check(private.has_permission(academy_id,null,'settings.write'));
create trigger audit_master after insert or update on public.payment_methods for each row execute function private.audit_master();
alter table public.accounts enable row level security;
grant select on public.accounts to authenticated;
create policy accounts_read on public.accounts for select to authenticated using (private.has_permission(academy_id,branch_id,'treasury.read'));
create trigger immutable_academy before update on public.accounts for each row execute function private.immutable_academy();
create index accounts_academy_idx on public.accounts(academy_id);
grant insert,update on public.accounts to authenticated;
create policy accounts_insert on public.accounts for insert to authenticated with check(private.has_permission(academy_id,branch_id,'treasury.write'));
create policy accounts_update on public.accounts for update to authenticated using(private.has_permission(academy_id,branch_id,'treasury.write')) with check(private.has_permission(academy_id,branch_id,'treasury.write'));
create trigger audit_master after insert or update on public.accounts for each row execute function private.audit_master();
alter table public.cash_sessions enable row level security;
grant select on public.cash_sessions to authenticated;
create policy cash_sessions_read on public.cash_sessions for select to authenticated using (private.has_permission(academy_id,branch_id,'treasury.read'));
create trigger immutable_academy before update on public.cash_sessions for each row execute function private.immutable_academy();
create index cash_sessions_academy_idx on public.cash_sessions(academy_id);
alter table public.payments enable row level security;
grant select on public.payments to authenticated;
create policy payments_read on public.payments for select to authenticated using (private.has_permission(academy_id,branch_id,'billing.read'));
create trigger immutable_academy before update on public.payments for each row execute function private.immutable_academy();
create index payments_academy_idx on public.payments(academy_id);
alter table public.payment_applications enable row level security;
grant select on public.payment_applications to authenticated;
create policy payment_applications_read on public.payment_applications for select to authenticated using (private.has_permission(academy_id,null,'billing.read') and exists(select 1 from public.charges parent where parent.id=payment_applications.charge_id and parent.academy_id=payment_applications.academy_id));
create trigger immutable_academy before update on public.payment_applications for each row execute function private.immutable_academy();
create index payment_applications_academy_idx on public.payment_applications(academy_id);
alter table public.account_movements enable row level security;
grant select on public.account_movements to authenticated;
create policy account_movements_read on public.account_movements for select to authenticated using (private.has_permission(academy_id,branch_id,'treasury.read'));
create trigger immutable_academy before update on public.account_movements for each row execute function private.immutable_academy();
create index account_movements_academy_idx on public.account_movements(academy_id);
alter table public.refunds enable row level security;
grant select on public.refunds to authenticated;
create policy refunds_read on public.refunds for select to authenticated using (private.has_permission(academy_id,branch_id,'billing.read'));
create trigger immutable_academy before update on public.refunds for each row execute function private.immutable_academy();
create index refunds_academy_idx on public.refunds(academy_id);
alter table public.refund_applications enable row level security;
grant select on public.refund_applications to authenticated;
create policy refund_applications_read on public.refund_applications for select to authenticated using (private.has_permission(academy_id,null,'billing.read') and exists(select 1 from public.payment_applications parent where parent.id=refund_applications.application_id and parent.academy_id=refund_applications.academy_id));
create trigger immutable_academy before update on public.refund_applications for each row execute function private.immutable_academy();
create index refund_applications_academy_idx on public.refund_applications(academy_id);
alter table public.transfers enable row level security;
grant select on public.transfers to authenticated;
create policy transfers_read on public.transfers for select to authenticated using (private.has_permission(academy_id,branch_id,'treasury.read'));
create trigger immutable_academy before update on public.transfers for each row execute function private.immutable_academy();
create index transfers_academy_idx on public.transfers(academy_id);
alter table public.commitments enable row level security;
grant select on public.commitments to authenticated;
create policy commitments_read on public.commitments for select to authenticated using (private.has_permission(academy_id,branch_id,'billing.read'));
create trigger immutable_academy before update on public.commitments for each row execute function private.immutable_academy();
create index commitments_academy_idx on public.commitments(academy_id);
grant insert,update on public.commitments to authenticated;
create policy commitments_insert on public.commitments for insert to authenticated with check(private.has_permission(academy_id,branch_id,'billing.write'));
create policy commitments_update on public.commitments for update to authenticated using(private.has_permission(academy_id,branch_id,'billing.write')) with check(private.has_permission(academy_id,branch_id,'billing.write'));
create trigger audit_master after insert or update on public.commitments for each row execute function private.audit_master();
alter table public.product_categories enable row level security;
grant select on public.product_categories to authenticated;
create policy product_categories_read on public.product_categories for select to authenticated using (private.has_permission(academy_id,null,'inventory.read'));
create trigger immutable_academy before update on public.product_categories for each row execute function private.immutable_academy();
create index product_categories_academy_idx on public.product_categories(academy_id);
grant insert,update on public.product_categories to authenticated;
create policy product_categories_insert on public.product_categories for insert to authenticated with check(private.has_permission(academy_id,null,'inventory.write'));
create policy product_categories_update on public.product_categories for update to authenticated using(private.has_permission(academy_id,null,'inventory.write')) with check(private.has_permission(academy_id,null,'inventory.write'));
create trigger audit_master after insert or update on public.product_categories for each row execute function private.audit_master();
alter table public.products enable row level security;
grant select on public.products to authenticated;
create policy products_read on public.products for select to authenticated using (private.has_permission(academy_id,null,'inventory.read'));
create trigger immutable_academy before update on public.products for each row execute function private.immutable_academy();
create index products_academy_idx on public.products(academy_id);
grant insert,update on public.products to authenticated;
create policy products_insert on public.products for insert to authenticated with check(private.has_permission(academy_id,null,'inventory.write'));
create policy products_update on public.products for update to authenticated using(private.has_permission(academy_id,null,'inventory.write')) with check(private.has_permission(academy_id,null,'inventory.write'));
create trigger audit_master after insert or update on public.products for each row execute function private.audit_master();
alter table public.product_variants enable row level security;
grant select on public.product_variants to authenticated;
create policy product_variants_read on public.product_variants for select to authenticated using (private.has_permission(academy_id,null,'inventory.read'));
create trigger immutable_academy before update on public.product_variants for each row execute function private.immutable_academy();
create index product_variants_academy_idx on public.product_variants(academy_id);
grant insert,update on public.product_variants to authenticated;
create policy product_variants_insert on public.product_variants for insert to authenticated with check(private.has_permission(academy_id,null,'inventory.write'));
create policy product_variants_update on public.product_variants for update to authenticated using(private.has_permission(academy_id,null,'inventory.write')) with check(private.has_permission(academy_id,null,'inventory.write'));
create trigger audit_master after insert or update on public.product_variants for each row execute function private.audit_master();
alter table public.stock enable row level security;
grant select on public.stock to authenticated;
create policy stock_read on public.stock for select to authenticated using (private.has_permission(academy_id,branch_id,'inventory.read'));
create trigger immutable_academy before update on public.stock for each row execute function private.immutable_academy();
create index stock_academy_idx on public.stock(academy_id);
alter table public.inventory_movements enable row level security;
grant select on public.inventory_movements to authenticated;
create policy inventory_movements_read on public.inventory_movements for select to authenticated using (private.has_permission(academy_id,branch_id,'inventory.read'));
create trigger immutable_academy before update on public.inventory_movements for each row execute function private.immutable_academy();
create index inventory_movements_academy_idx on public.inventory_movements(academy_id);
alter table public.suppliers enable row level security;
grant select on public.suppliers to authenticated;
create policy suppliers_read on public.suppliers for select to authenticated using (private.has_permission(academy_id,null,'inventory.read'));
create trigger immutable_academy before update on public.suppliers for each row execute function private.immutable_academy();
create index suppliers_academy_idx on public.suppliers(academy_id);
grant insert,update on public.suppliers to authenticated;
create policy suppliers_insert on public.suppliers for insert to authenticated with check(private.has_permission(academy_id,null,'inventory.write'));
create policy suppliers_update on public.suppliers for update to authenticated using(private.has_permission(academy_id,null,'inventory.write')) with check(private.has_permission(academy_id,null,'inventory.write'));
create trigger audit_master after insert or update on public.suppliers for each row execute function private.audit_master();
alter table public.expenses enable row level security;
grant select on public.expenses to authenticated;
create policy expenses_read on public.expenses for select to authenticated using (private.has_permission(academy_id,branch_id,'expenses.read'));
create trigger immutable_academy before update on public.expenses for each row execute function private.immutable_academy();
create index expenses_academy_idx on public.expenses(academy_id);
alter table public.expense_payments enable row level security;
grant select on public.expense_payments to authenticated;
create policy expense_payments_read on public.expense_payments for select to authenticated using (private.has_permission(academy_id,branch_id,'expenses.read'));
create trigger immutable_academy before update on public.expense_payments for each row execute function private.immutable_academy();
create index expense_payments_academy_idx on public.expense_payments(academy_id);
alter table public.expense_templates enable row level security;
grant select on public.expense_templates to authenticated;
create policy expense_templates_read on public.expense_templates for select to authenticated using (private.has_permission(academy_id,branch_id,'expenses.read'));
create trigger immutable_academy before update on public.expense_templates for each row execute function private.immutable_academy();
create index expense_templates_academy_idx on public.expense_templates(academy_id);
grant insert,update on public.expense_templates to authenticated;
create policy expense_templates_insert on public.expense_templates for insert to authenticated with check(private.has_permission(academy_id,branch_id,'expenses.write'));
create policy expense_templates_update on public.expense_templates for update to authenticated using(private.has_permission(academy_id,branch_id,'expenses.write')) with check(private.has_permission(academy_id,branch_id,'expenses.write'));
create trigger audit_master after insert or update on public.expense_templates for each row execute function private.audit_master();
alter table public.purchases enable row level security;
grant select on public.purchases to authenticated;
create policy purchases_read on public.purchases for select to authenticated using (private.has_permission(academy_id,branch_id,'inventory.read'));
create trigger immutable_academy before update on public.purchases for each row execute function private.immutable_academy();
create index purchases_academy_idx on public.purchases(academy_id);
alter table public.purchase_lines enable row level security;
grant select on public.purchase_lines to authenticated;
create policy purchase_lines_read on public.purchase_lines for select to authenticated using (private.has_permission(academy_id,null,'inventory.read') and exists(select 1 from public.purchases parent where parent.id=purchase_lines.purchase_id and parent.academy_id=purchase_lines.academy_id));
create trigger immutable_academy before update on public.purchase_lines for each row execute function private.immutable_academy();
create index purchase_lines_academy_idx on public.purchase_lines(academy_id);
alter table public.stock_transfers enable row level security;
grant select on public.stock_transfers to authenticated;
create policy stock_transfers_read on public.stock_transfers for select to authenticated using (private.has_permission(academy_id,branch_id,'inventory.read'));
create trigger immutable_academy before update on public.stock_transfers for each row execute function private.immutable_academy();
create index stock_transfers_academy_idx on public.stock_transfers(academy_id);
alter table public.equipment enable row level security;
grant select on public.equipment to authenticated;
create policy equipment_read on public.equipment for select to authenticated using (private.has_permission(academy_id,branch_id,'inventory.read'));
create trigger immutable_academy before update on public.equipment for each row execute function private.immutable_academy();
create index equipment_academy_idx on public.equipment(academy_id);
grant insert,update on public.equipment to authenticated;
create policy equipment_insert on public.equipment for insert to authenticated with check(private.has_permission(academy_id,branch_id,'inventory.write'));
create policy equipment_update on public.equipment for update to authenticated using(private.has_permission(academy_id,branch_id,'inventory.write')) with check(private.has_permission(academy_id,branch_id,'inventory.write'));
create trigger audit_master after insert or update on public.equipment for each row execute function private.audit_master();
alter table public.sales enable row level security;
grant select on public.sales to authenticated;
create policy sales_read on public.sales for select to authenticated using (private.has_permission(academy_id,branch_id,'sales.read'));
create trigger immutable_academy before update on public.sales for each row execute function private.immutable_academy();
create index sales_academy_idx on public.sales(academy_id);
alter table public.sale_lines enable row level security;
grant select on public.sale_lines to authenticated;
create policy sale_lines_read on public.sale_lines for select to authenticated using (private.has_permission(academy_id,null,'sales.read') and exists(select 1 from public.sales parent where parent.id=sale_lines.sale_id and parent.academy_id=sale_lines.academy_id));
create trigger immutable_academy before update on public.sale_lines for each row execute function private.immutable_academy();
create index sale_lines_academy_idx on public.sale_lines(academy_id);
alter table public.employees enable row level security;
grant select on public.employees to authenticated;
create policy employees_read on public.employees for select to authenticated using (private.has_permission(academy_id,branch_id,'staff.read'));
create trigger immutable_academy before update on public.employees for each row execute function private.immutable_academy();
create index employees_academy_idx on public.employees(academy_id);
grant insert,update on public.employees to authenticated;
create policy employees_insert on public.employees for insert to authenticated with check(private.has_permission(academy_id,branch_id,'staff.write'));
create policy employees_update on public.employees for update to authenticated using(private.has_permission(academy_id,branch_id,'staff.write')) with check(private.has_permission(academy_id,branch_id,'staff.write'));
create trigger audit_master after insert or update on public.employees for each row execute function private.audit_master();
alter table public.compensation_versions enable row level security;
grant select on public.compensation_versions to authenticated;
create policy compensation_versions_read on public.compensation_versions for select to authenticated using (private.has_permission(academy_id,null,'staff.read') and exists(select 1 from public.employees parent where parent.id=compensation_versions.employee_id and parent.academy_id=compensation_versions.academy_id));
create trigger immutable_academy before update on public.compensation_versions for each row execute function private.immutable_academy();
create index compensation_versions_academy_idx on public.compensation_versions(academy_id);
alter table public.staff_activities enable row level security;
grant select on public.staff_activities to authenticated;
create policy staff_activities_read on public.staff_activities for select to authenticated using (private.has_permission(academy_id,branch_id,'staff.read'));
create trigger immutable_academy before update on public.staff_activities for each row execute function private.immutable_academy();
create index staff_activities_academy_idx on public.staff_activities(academy_id);
alter table public.settlements enable row level security;
grant select on public.settlements to authenticated;
create policy settlements_read on public.settlements for select to authenticated using (private.has_permission(academy_id,branch_id,'staff.read'));
create trigger immutable_academy before update on public.settlements for each row execute function private.immutable_academy();
create index settlements_academy_idx on public.settlements(academy_id);
alter table public.settlement_lines enable row level security;
grant select on public.settlement_lines to authenticated;
create policy settlement_lines_read on public.settlement_lines for select to authenticated using (private.has_permission(academy_id,null,'staff.read') and exists(select 1 from public.settlements parent where parent.id=settlement_lines.settlement_id and parent.academy_id=settlement_lines.academy_id));
create trigger immutable_academy before update on public.settlement_lines for each row execute function private.immutable_academy();
create index settlement_lines_academy_idx on public.settlement_lines(academy_id);
alter table public.class_templates enable row level security;
grant select on public.class_templates to authenticated;
create policy class_templates_read on public.class_templates for select to authenticated using (private.has_permission(academy_id,branch_id,'classes.read'));
create trigger immutable_academy before update on public.class_templates for each row execute function private.immutable_academy();
create index class_templates_academy_idx on public.class_templates(academy_id);
grant insert,update on public.class_templates to authenticated;
create policy class_templates_insert on public.class_templates for insert to authenticated with check(private.has_permission(academy_id,branch_id,'classes.write'));
create policy class_templates_update on public.class_templates for update to authenticated using(private.has_permission(academy_id,branch_id,'classes.write')) with check(private.has_permission(academy_id,branch_id,'classes.write'));
create trigger audit_master after insert or update on public.class_templates for each row execute function private.audit_master();
alter table public.classes enable row level security;
grant select on public.classes to authenticated;
create policy classes_read on public.classes for select to authenticated using (private.has_permission(academy_id,branch_id,'classes.read'));
create trigger immutable_academy before update on public.classes for each row execute function private.immutable_academy();
create index classes_academy_idx on public.classes(academy_id);
alter table public.reservations enable row level security;
grant select on public.reservations to authenticated;
create policy reservations_read on public.reservations for select to authenticated using (private.has_permission(academy_id,branch_id,'classes.read'));
create trigger immutable_academy before update on public.reservations for each row execute function private.immutable_academy();
create index reservations_academy_idx on public.reservations(academy_id);
alter table public.attendance enable row level security;
grant select on public.attendance to authenticated;
create policy attendance_read on public.attendance for select to authenticated using (private.has_permission(academy_id,branch_id,'classes.read'));
create trigger immutable_academy before update on public.attendance for each row execute function private.immutable_academy();
create index attendance_academy_idx on public.attendance(academy_id);
alter table public.holidays enable row level security;
grant select on public.holidays to authenticated;
create policy holidays_read on public.holidays for select to authenticated using (private.has_permission(academy_id,branch_id,'classes.read'));
create trigger immutable_academy before update on public.holidays for each row execute function private.immutable_academy();
create index holidays_academy_idx on public.holidays(academy_id);
grant insert,update on public.holidays to authenticated;
create policy holidays_insert on public.holidays for insert to authenticated with check(private.has_permission(academy_id,branch_id,'classes.write'));
create policy holidays_update on public.holidays for update to authenticated using(private.has_permission(academy_id,branch_id,'classes.write')) with check(private.has_permission(academy_id,branch_id,'classes.write'));
create trigger audit_master after insert or update on public.holidays for each row execute function private.audit_master();
alter table public.notifications enable row level security;
grant select on public.notifications to authenticated;
create policy notifications_read on public.notifications for select to authenticated using (private.has_permission(academy_id,branch_id,'reports.read'));
create trigger immutable_academy before update on public.notifications for each row execute function private.immutable_academy();
create index notifications_academy_idx on public.notifications(academy_id);
alter table public.audit_log enable row level security;
grant select on public.audit_log to authenticated;
create policy audit_log_read on public.audit_log for select to authenticated using (private.has_permission(academy_id,branch_id,'audit.read'));
create trigger immutable_academy before update on public.audit_log for each row execute function private.immutable_academy();
create index audit_log_academy_idx on public.audit_log(academy_id);
alter table public.operation_keys enable row level security;
grant select on public.operation_keys to authenticated;
create policy operation_keys_read on public.operation_keys for select to authenticated using (private.has_permission(academy_id,null,'audit.read'));
create trigger immutable_academy before update on public.operation_keys for each row execute function private.immutable_academy();
create index operation_keys_academy_idx on public.operation_keys(academy_id);
alter table public.job_runs enable row level security;
grant select on public.job_runs to authenticated;
create policy job_runs_read on public.job_runs for select to authenticated using (private.has_permission(academy_id,null,'billing.read'));
create trigger immutable_academy before update on public.job_runs for each row execute function private.immutable_academy();
create index job_runs_academy_idx on public.job_runs(academy_id);
alter table public.document_counters enable row level security;
grant select on public.document_counters to authenticated;
create policy document_counters_read on public.document_counters for select to authenticated using (private.has_permission(academy_id,null,'settings.read'));
create trigger immutable_academy before update on public.document_counters for each row execute function private.immutable_academy();
create index document_counters_academy_idx on public.document_counters(academy_id);

create index charges_due_idx on public.charges(academy_id,branch_id,due_on);
create index students_search_idx on public.students(academy_id,lower(name));
create index memberships_due_idx on public.memberships(academy_id,next_charge_on) where status='activa';
create index movements_account_idx on public.account_movements(account_id,created_at);
create index applications_charge_idx on public.payment_applications(charge_id);
create index classes_time_idx on public.classes(branch_id,starts_at,ends_at);
create index roles_member_idx on public.member_roles(member_id);
create index audit_time_idx on public.audit_log(academy_id,created_at desc);
create view public.charge_balances with(security_invoker=true) as
 select c.*, c.amount+coalesce((select sum(ca.amount) from public.charge_adjustments ca where ca.charge_id=c.id),0)-coalesce((select sum(pa.amount) from public.payment_applications pa where pa.charge_id=c.id and pa.confirmed),0)
 +coalesce((select sum(ra.amount) from public.refund_applications ra join public.payment_applications pa on pa.id=ra.application_id where pa.charge_id=c.id),0) as balance
 from public.charges c where c.status='emitido';
grant select on public.charge_balances to authenticated;
create view public.account_balances with(security_invoker=true) as select a.*, coalesce((select sum(m.amount) from public.account_movements m where m.account_id=a.id),0) as balance from public.accounts a;
grant select on public.account_balances to authenticated;
create view public.expense_balances with(security_invoker=true) as select e.*,e.amount-coalesce((select sum(p.amount) from public.expense_payments p where p.expense_id=e.id),0) as balance from public.expenses e where status<>'anulado';
grant select on public.expense_balances to authenticated;
